In [1]:
import torch
import torchvision
# from torch.utils.tensorboard import SummaryWriter
import time
from torch import nn
from torch.utils.data import DataLoader
from load_data import MyData  # self-made
from torchvision import transforms
from tqdm import tqdm_notebook as tqdm # View procedure
import os
import scipy.io
from random import random
import numpy as np
import gc
from torch.utils.tensorboard import SummaryWriter
from net_cnn_lstm1 import MyNetwork
from torchnlp.word_to_vector import GloVe
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [2]:
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ random
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ optimizer
import torch.optim as optim
device = torch.device("cuda:0")
gc.collect()
torch.cuda.empty_cache()
# ==损失函数权重
# ======== 二分类HC/DOC
# 计算总样本数量
# condition1
# total_samples = 887 + 985 + 879
# condition2
# total_samples = 929 + 1029 + 886
# condition3
# total_samples = 887 + 975 + 879
# rest
# total_samples = 852 + 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 887, total_samples / (985 + 879)]
# condition2
# weights = [total_samples / 929, total_samples / (1029 + 886)]
# rest
# weights = [total_samples / 852, total_samples / (1051 + 872)]

# ======== 二分类MCS/UWS
# 计算总样本数量
# condition1
# total_samples = 985 + 879
# condition2
# total_samples = 1029 + 886
# condition3
# total_samples = 975 + 879
# rest
total_samples = 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 985, total_samples / 879]
# condition2
# weights = [total_samples / 1029, total_samples / 886]
# condition3
# weights = [total_samples / 975, total_samples / 879]
# rest
weights = [total_samples / 1051, total_samples / 872]
# 将权重转换为张量
weights_tensor = torch.tensor(weights, device=device)

# 定义交叉熵损失函数并设置权重
criterion = nn.CrossEntropyLoss(weight=weights_tensor)
# criterion = nn.CrossEntropyLoss()
criterion = criterion.to(device)

In [3]:
def make_dataset(dataset,mode):
    # find the fold file
    count = 0
    for person in range(len(dataset)):
        filename = os.path.join(dataset.path, dataset.file_path[person])
        # extract the pure name of the file
        parts = filename.split("\\")
        file_name = parts[-1]
        name_without_extension = file_name.split(".")[0]
        # label or data
        file_last = name_without_extension.split("_")[-1]
        if file_last.isdigit(): # data
            # is this fold or not
            if int(file_last) == fold: # yes
                print(filename)
                count = count + 1
                data_map = torch.load(filename)
                # train or test
                if name_without_extension.split("_")[-2] == "train":
                    for i in range(data_map.size(0)):
                        train_data.append(data_map[i])
                elif name_without_extension.split("_")[-2] == "test":
                    for i in range(data_map.size(0)):
                        test_data.append(data_map[i])
                if count == 4:
                    del data_map
                    gc.collect()
                    torch.cuda.empty_cache() 
                    break
            else:   # not
                pass
        else: # label
            file_last = name_without_extension.split("_")[-4]
            file_mode = name_without_extension.split("_")[-2]
            if file_mode == mode.split("_")[-1]: # is this mode or not
                # is this fold or not
                if int(file_last) == fold: # yes
                    print(filename)
                    count = count + 1
                    data_map = torch.load(filename)
                    # train or test
                    if name_without_extension.split("_")[-5] == "train":
                        for i in range(data_map.size(0)):
                            train_label.append(data_map[i])
                    elif name_without_extension.split("_")[-5] == "test":
                        for i in range(data_map.size(0)):
                            test_label.append(data_map[i])
                    if count == 4:
                        del data_map
                        gc.collect()
                        torch.cuda.empty_cache() 
                        break
                else:   # not
                    pass
            else:
                pass
        del filename, parts, file_name, name_without_extension, file_last
        gc.collect()
        torch.cuda.empty_cache()    
# 定义LSTM超参数
input_size = 64  # 输入特征维度
# hidden_size = 64  # 隐藏单元数量
# input_size = 59  # 输入特征维度
hidden_size = 64  # 隐藏单元数量
num_layers = 2  # LSTM层数
output_size = 2  # 输出类别数量
# 创建模型实例
# model_list = ['', '_CNN', '_CNN_spa', '_CNN_spa_lstm']
# model_name = model_list[0]
# if model_name == model_list[0]: #  CascadeCept
#     from network_cnn_lstm import MyNetwork
# elif model_name == model_list[1]: #  CNN
#     from network_cnn_lstm_2 import MyNetwork
# elif model_name == model_list[2]: # CascadeCept_1
#     from network_cnn_lstm_3 import MyNetwork
# elif model_name == model_list[3]: # CascadeCept_2
#     from network_cnn_lstm_4 import MyNetwork
model_list = ['_1', '_2', '_3', '_4','_5','_6','_7','_8','_9','_10','_11']
model_name = model_list[0]
if model_name == model_list[0]: 
    from net_cnn_lstm1 import MyNetwork
elif model_name == model_list[1]: 
    from net_cnn_lstm2 import MyNetwork
elif model_name == model_list[2]: 
    from net_cnn_lstm3 import MyNetwork
elif model_name == model_list[3]: 
    from net_cnn_lstm4 import MyNetwork
elif model_name == model_list[4]: 
    from net_cnn_lstm5 import MyNetwork
elif model_name == model_list[5]: 
    from net_cnn_lstm6 import MyNetwork
elif model_name == model_list[6]: 
    from net_cnn_lstm7 import MyNetwork
elif model_name == model_list[7]: 
    from net_cnn_lstm8 import MyNetwork
elif model_name == model_list[8]: 
    from net_cnn_lstm9 import MyNetwork
elif model_name == model_list[9]: 
    from net_cnn_lstm10 import MyNetwork
elif model_name == model_list[10]: 
    from net_cnn_lstm11 import MyNetwork
model = MyNetwork(input_size, hidden_size, num_layers, output_size)
model = model.to(device)

# experimental dir: rest, conditionA, conditionB, conditionC
exper_dir = "rest"
trial="_1"
# root_dir = f"../data/eegmap_split/{exper_dir}"
root_dir = f"../data/eegmap_split_new/{exper_dir}"
# classification = "hc_doc"/doc or "mcs_uws"/uws
# classification = "hc_doc"
classification = "mcs_uws"
fold_num = 5
best_val_loss = float('inf')
for fold in tqdm(range(5)):
    # train num folds
#     fold = 0 # 选择折数
    # -- prepare datasets
    train_data = []
    train_label = []
    test_data = []
    test_label = []
    
    if classification == "hc_doc":
        # ---- hc
        dataset = MyData(root_dir, "train", "hc") # hc
        make_dataset(dataset,classification)
        dataset = MyData(root_dir, "test", "hc") # hc
        make_dataset(dataset,classification)
    # ---- mcs
    dataset = MyData(root_dir, "train", "mcs") # mcs
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "mcs") # hc
    make_dataset(dataset,classification)
    # ---- uws
    dataset = MyData(root_dir, "train", "uws") # uws
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "uws") # hc
    make_dataset(dataset,classification)
    
    print(torch.stack(train_data).size())
    print(torch.stack(train_label).size())
    print(torch.stack(test_data).size())
    print(torch.stack(test_label).size())
    del dataset
    gc.collect()
    torch.cuda.empty_cache()  
    
    train_data = torch.stack(train_data)
    train_label = torch.stack(train_label)
    test_data = torch.stack(test_data)
    test_label = torch.stack(test_label)
    # train dataset
    train_td = TensorDataset(train_data, train_label)
    train_loader = DataLoader(train_td, batch_size = BATCH_SIZE, shuffle = True)
    # test dataset
    test_td = TensorDataset(test_data, test_label)
    test_loader = DataLoader(test_td, batch_size = BATCH_SIZE, shuffle = True)
    del train_data, train_label, test_data, test_label, train_td, test_td
    gc.collect()
    torch.cuda.empty_cache()
    
    # set model for each fold
    model = MyNetwork(input_size, hidden_size, num_layers, output_size)
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr = learn_rate)
    scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 30, 50], gamma=0.2)
#     scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5, verbose=True)
    # -- start training
    start_time = time.time()
    # train and test step records
    total_train_step = 0
    total_test_step = 0
    min_test_loss = 1000
    # add Tensorboard
#     writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_train_{fold}")
#     writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_{fold}")
#     writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_acc_{fold}")
    writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_train_{fold}")
    writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_{fold}")
    writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_acc_{fold}")
    for i in tqdm(range(num_epochs)):  
        print(f"========= Epoch {i} Training =========")
        # train steps
        model.train()
        for data in train_loader:
            # x, y
            data_map, label=data
            data_map_reshaped = torch.reshape(data_map, (99, 1, 1, 2400))
#             data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
            label_int = label.long()
            data_map_reshaped=data_map_reshaped.to(device)
            label_int=label_int.to(device)
            del data_map, label
            gc.collect()
            torch.cuda.empty_cache()
            # y_pred
            label_pred = model(data_map_reshaped)
            # Loss Computation and Optimization
            loss = criterion(label_pred,label_int)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            # draw tensorboard
            total_train_step = total_train_step + 1
            # print info
            if total_train_step % 500 == 0:
                end_time = time.time()
                print(label_pred)
                print(f"Train time: {end_time - start_time}")
                print(f"Train steps: {total_train_step}, Loss: {loss.item()}")
            writer_train.add_scalar("train_loss",loss.item(),total_train_step)
            # Clear gpu
            del data, data_map_reshaped, label_int, label_pred, loss
            gc.collect()
            torch.cuda.empty_cache()
        
        # Evaluation and save the best model
        print(f"========= Epoch {i} Testing =========")
        model.eval()
        test_loss = 0
        total_test_loss = 0
        test_count = 0
        total_test_acc = 0
        with torch.no_grad():
            for data in test_loader:
                test_count = test_count + 1
                # x, y
                data_map, label=data
                data_map_reshaped = torch.reshape(data_map, (99, 1, 1, 2400))
#                 data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
                label_int = label.long()
                data_map_reshaped = data_map_reshaped.to(device)
                label_int = label_int.to(device)
                del data_map, label
                gc.collect()
                torch.cuda.empty_cache()
                # y_pred
                label_pred_test = model(data_map_reshaped)
                loss = criterion(label_pred_test,label_int)
#                 print(label_pred_test)
                # accuracy 
                total_test_acc = total_test_acc + ((label_pred_test.argmax(1)) == label_int).sum()
                # change lr
                test_loss += loss.item()
                test_loss /= len(test_loader)
                if test_loss < best_val_loss:
                    best_val_loss = test_loss
                scheduler.step()
                # draw tensorboad
                total_test_loss = total_test_loss + loss
                if test_count % 100 == 0:
                    print(f"Loss: {total_test_loss} Accuracy: {total_test_acc/test_count}")
                # Clear gpu
                del data_map_reshaped, label_int, label_pred_test, loss, data
                gc.collect()
                torch.cuda.empty_cache()
        print(f"Total Loss: {total_test_loss} Total Accuracy: {total_test_acc/test_count}")
        writer_valid.add_scalar("test_loss", total_test_loss, total_test_step)
        writer_valid_acc.add_scalar("test_acc", total_test_acc/test_count, total_test_step)
        total_test_step = total_test_step + 1
        print("..........Saving the model..........")
#         torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}/Fold{fold}_Epoch{i}.pt") 
        torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}{trial}/Fold{fold}_Epoch{i}.pt") 
#         if total_test_loss < min_test_loss:
#             min_test_loss = total_test_loss
#             print("..........Saving the model..........")
#             torch.save(model.state_dict(),f"../model/{exper_dir}/Fold{fold}_Epoch{i}.pt")

D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:115: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/5 [00:00<?, ?it/s]

../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_0.pt
../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_0_mcs_uws_label.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_0.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_0_mcs_uws_label.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_0.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_0_mcs_uws_label.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_0.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_0_mcs_uws_label.pt
torch.Size([1539, 2400, 9, 11])
torch.Size([1539])
torch.Size([384, 2400, 9, 11])
torch.Size([384])


D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:182: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[ 0.1820, -0.0374]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 39.94621133804321
Train steps: 500, Loss: 0.8088173866271973
tensor([[ 0.5286, -0.5074]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 76.60537505149841
Train steps: 1000, Loss: 1.339674472808838
tensor([[ 0.0875, -0.0222]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 113.49560952186584
Train steps: 1500, Loss: 0.6397587060928345
========= Epoch 0 Testing =========
Loss: 69.27685546875 Accuracy: 0.5199999809265137
Loss: 138.5709991455078 Accuracy: 0.5199999809265137
Loss: 206.27679443359375 Accuracy: 0.5566666722297668
Total Loss: 264.574462890625 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 0.0921, -0.0520]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 177.22043871879578
Train steps: 2000, Loss: 0.62368243932724
tensor([[ 0.1024, -0.0460]], device='cuda:0', grad_fn=<Addmm

Loss: 208.03530883789062 Accuracy: 0.5266667008399963
Total Loss: 266.433837890625 Total Accuracy: 0.515625
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 0.1077, -0.0634]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1588.1573247909546
Train steps: 17000, Loss: 0.7823415994644165
tensor([[0.0602, 0.0594]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1624.2078540325165
Train steps: 17500, Loss: 0.6927463412284851
tensor([[ 0.1303, -0.1571]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1662.0772750377655
Train steps: 18000, Loss: 0.5597260594367981
========= Epoch 11 Testing =========
Loss: 68.57723236083984 Accuracy: 0.5099999904632568
Loss: 138.78762817382812 Accuracy: 0.4899999797344208
Loss: 208.07980346679688 Accuracy: 0.48000001907348633
Total Loss: 267.6018371582031 Total Accuracy: 0.4661458432674408
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[ 0.1278, -0.0873]], device=

tensor([[-2.0571,  3.0033]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3057.6152510643005
Train steps: 33000, Loss: 0.006322501227259636
tensor([[-1.8844,  2.7615]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3095.027631044388
Train steps: 33500, Loss: 0.009555081836879253
========= Epoch 21 Testing =========
Loss: 208.5065155029297 Accuracy: 0.4599999785423279
Loss: 444.66461181640625 Accuracy: 0.4399999976158142
Loss: 621.4478759765625 Accuracy: 0.4699999988079071
Total Loss: 775.3487548828125 Total Accuracy: 0.4895833432674408
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[-2.1930,  3.1683]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3162.5921971797943
Train steps: 34000, Loss: 0.00468395184725523
tensor([[-2.2324,  3.2092]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3198.739312648773
Train steps: 34500, Loss: 0.00432318402454257
tensor([[ 1.6941, -2.1637]], device='cuda:0', grad_fn=<AddmmBackwar

========= Epoch 31 Testing =========
Loss: 356.4659729003906 Accuracy: 0.5199999809265137
Loss: 660.0914916992188 Accuracy: 0.5249999761581421
Loss: 1027.7161865234375 Accuracy: 0.5099999904632568
Total Loss: 1382.9891357421875 Total Accuracy: 0.4895833432674408
..........Saving the model..........
========= Epoch 32 Training =========
tensor([[ 3.5104, -4.2011]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4592.774841308594
Train steps: 49500, Loss: 0.000447530735982582
tensor([[-4.0219,  5.0905]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4628.666093826294
Train steps: 50000, Loss: 0.0001102625101339072
tensor([[-3.8821,  4.8658]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4664.711894035339
Train steps: 50500, Loss: 0.00015877417172305286
========= Epoch 32 Testing =========
Loss: 372.143798828125 Accuracy: 0.5299999713897705
Loss: 764.0468139648438 Accuracy: 0.4949999749660492
Loss: 1174.2957763671875 Accuracy: 0.49000000953674316
Total Loss: 149

tensor([[ 4.0253, -4.7943]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6074.793670415878
Train steps: 65000, Loss: 0.00014780859055463225
tensor([[-4.4335,  5.5021]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6144.146038770676
Train steps: 65500, Loss: 4.8397800128441304e-05
tensor([[ 4.2023, -4.9724]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6201.528265953064
Train steps: 66000, Loss: 0.00010358751023886725
========= Epoch 42 Testing =========
Loss: 424.284423828125 Accuracy: 0.4899999797344208
Loss: 871.9124145507812 Accuracy: 0.4699999988079071
Loss: 1310.31884765625 Accuracy: 0.46666666865348816
Total Loss: 1636.6348876953125 Total Accuracy: 0.4765625
..........Saving the model..........
========= Epoch 43 Training =========
tensor([[ 4.0499, -4.7320]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6280.150027751923
Train steps: 66500, Loss: 0.0001535297924419865
tensor([[-4.3479,  5.4513]], device='cuda:0', grad_fn=<AddmmBackward0>

tensor([[ 6.0940, -7.0540]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8398.409512758255
Train steps: 81500, Loss: 1.9073468138230965e-06
========= Epoch 52 Testing =========
Loss: 656.2569580078125 Accuracy: 0.4699999988079071
Loss: 1329.73486328125 Accuracy: 0.4599999785423279
Loss: 2017.7615966796875 Accuracy: 0.45000001788139343
Total Loss: 2570.10400390625 Total Accuracy: 0.4505208432674408
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[ 6.3015, -7.2951]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8472.292082548141
Train steps: 82000, Loss: 1.1920922133867862e-06
tensor([[-6.0960,  7.1380]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8519.13931965828
Train steps: 82500, Loss: 1.7881378653328284e-06
tensor([[-6.4319,  7.5212]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8568.767047643661
Train steps: 83000, Loss: 8.344646857949556e-07
========= Epoch 53 Testing =========
Loss: 594.7922973632812 A

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[ 0.0387, -0.1104]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 38.37815880775452
Train steps: 500, Loss: 0.6213524341583252
tensor([[ 0.0991, -0.1389]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 77.21009612083435
Train steps: 1000, Loss: 0.5812163352966309
tensor([[ 0.0657, -0.0981]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 120.4807550907135
Train steps: 1500, Loss: 0.6145937442779541
========= Epoch 0 Testing =========
Loss: 70.6358642578125 Accuracy: 0.4699999988079071
Loss: 137.5528564453125 Accuracy: 0.5450000166893005
Loss: 206.5216064453125 Accuracy: 0.54666668176651
Total Loss: 264.3661804199219 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 0.1073, -0.1485]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 190.23328971862793
Train steps: 2000, Loss: 0.5734130144119263
tensor([[ 0.1112, -0.1743]], device='cuda:0', grad_fn=<Add

Loss: 69.37179565429688 Accuracy: 0.5399999618530273
Loss: 138.38067626953125 Accuracy: 0.5600000023841858
Loss: 203.97433471679688 Accuracy: 0.5833333730697632
Total Loss: 263.1689758300781 Total Accuracy: 0.578125
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[-0.1057, -0.0107]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1662.993169784546
Train steps: 17000, Loss: 0.6468138694763184
tensor([[-0.1623,  0.0407]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1705.1437883377075
Train steps: 17500, Loss: 0.7998200058937073
tensor([[-0.0562, -0.0437]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1743.3354005813599
Train steps: 18000, Loss: 0.6994383335113525
========= Epoch 11 Testing =========
Loss: 65.5764389038086 Accuracy: 0.6299999952316284
Loss: 132.7191619873047 Accuracy: 0.6200000047683716
Loss: 206.06040954589844 Accuracy: 0.5800000429153442
Total Loss: 267.2215881347656 Total Accuracy: 0.5833333730697632
.....

tensor([[-1.5457,  1.3130]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3218.1307559013367
Train steps: 33000, Loss: 0.05575938895344734
tensor([[-0.7822,  0.6794]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3258.7227654457092
Train steps: 33500, Loss: 0.20853658020496368
========= Epoch 21 Testing =========
Loss: 108.59151458740234 Accuracy: 0.5
Loss: 223.40576171875 Accuracy: 0.48499998450279236
Loss: 328.8924865722656 Accuracy: 0.5200000405311584
Total Loss: 403.6945495605469 Total Accuracy: 0.5338541865348816
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[ 1.5226, -1.3104]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3328.704739332199
Train steps: 34000, Loss: 0.057170964777469635
tensor([[ 1.4355, -1.2656]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3370.052772283554
Train steps: 34500, Loss: 0.06497221440076828
tensor([[ 1.1336, -0.9720]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 

========= Epoch 31 Testing =========
Loss: 158.544189453125 Accuracy: 0.5399999618530273
Loss: 319.69244384765625 Accuracy: 0.5049999952316284
Loss: 548.4212646484375 Accuracy: 0.4766666889190674
Total Loss: 680.944580078125 Total Accuracy: 0.4947916865348816
..........Saving the model..........
========= Epoch 32 Training =========
tensor([[-3.1868,  3.0068]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4845.831997156143
Train steps: 49500, Loss: 0.0020404488313943148
tensor([[ 3.4992, -3.1181]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4888.228506565094
Train steps: 50000, Loss: 0.001336158369667828
tensor([[-3.1068,  2.9320]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4927.520762205124
Train steps: 50500, Loss: 0.002381704980507493
========= Epoch 32 Testing =========
Loss: 220.6781005859375 Accuracy: 0.4399999976158142
Loss: 418.9698791503906 Accuracy: 0.4599999785423279
Loss: 591.8750610351562 Accuracy: 0.4833333492279053
Total Loss: 739.49279

tensor([[ 5.6992, -5.1292]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6369.335041999817
Train steps: 65000, Loss: 1.97885437955847e-05
tensor([[ 5.6576, -5.1957]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6406.790750980377
Train steps: 65500, Loss: 1.9311717551317997e-05
tensor([[ 6.0697, -5.5953]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6447.159748077393
Train steps: 66000, Loss: 8.583032467868179e-06
========= Epoch 42 Testing =========
Loss: 326.45489501953125 Accuracy: 0.5099999904632568
Loss: 688.0778198242188 Accuracy: 0.5299999713897705
Loss: 1007.1376342773438 Accuracy: 0.5233333706855774
Total Loss: 1302.5621337890625 Total Accuracy: 0.5130208730697632
..........Saving the model..........
========= Epoch 43 Training =========
tensor([[ 5.6693, -5.2065]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6514.394708633423
Train steps: 66500, Loss: 1.8954096958623268e-05
tensor([[ 5.9639, -5.4891]], device='cuda:0', grad_fn=<Addmm

tensor([[ 8.7956, -8.1804]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7954.660925865173
Train steps: 81500, Loss: 0.0
========= Epoch 52 Testing =========
Loss: 483.0280456542969 Accuracy: 0.550000011920929
Loss: 970.776611328125 Accuracy: 0.5399999618530273
Loss: 1565.534912109375 Accuracy: 0.5133333206176758
Total Loss: 2045.2587890625 Total Accuracy: 0.5026041865348816
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[ 8.6615, -8.0748]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8022.066946029663
Train steps: 82000, Loss: 0.0
tensor([[ 9.0599, -8.5365]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8059.804092407227
Train steps: 82500, Loss: 0.0
tensor([[ 8.7042, -8.0844]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8100.704447984695
Train steps: 83000, Loss: 0.0
========= Epoch 53 Testing =========
Loss: 611.099609375 Accuracy: 0.44999998807907104
Loss: 1125.5517578125 Accuracy: 0.4749999940395355
Lo

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[ 0.4315, -0.2636]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 40.44909977912903
Train steps: 500, Loss: 0.40481096506118774
tensor([[ 0.2646, -0.0732]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 81.14809131622314
Train steps: 1000, Loss: 0.5384496450424194
tensor([[0.0205, 0.0662]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 122.29222798347473
Train steps: 1500, Loss: 0.6705491542816162
========= Epoch 0 Testing =========
Loss: 69.25089263916016 Accuracy: 0.5
Loss: 137.39085388183594 Accuracy: 0.5349999666213989
Loss: 205.4352264404297 Accuracy: 0.5566666722297668
Total Loss: 263.5000915527344 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 0.1690, -0.0083]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 187.48468589782715
Train steps: 2000, Loss: 0.785729169845581
tensor([[0.0733, 0.0135]], device='cuda:0', grad_fn=<AddmmBackward0>)


Loss: 137.89169311523438 Accuracy: 0.5299999713897705
Loss: 203.8903045654297 Accuracy: 0.5533333420753479
Total Loss: 259.7966613769531 Total Accuracy: 0.5651041865348816
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 0.1336, -0.0183]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1687.993376493454
Train steps: 17000, Loss: 0.6200588941574097
tensor([[ 0.2059, -0.0564]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1730.2785470485687
Train steps: 17500, Loss: 0.8328426480293274
tensor([[ 0.4545, -0.2367]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1771.859347820282
Train steps: 18000, Loss: 0.4061097502708435
========= Epoch 11 Testing =========
Loss: 70.36460876464844 Accuracy: 0.47999998927116394
Loss: 136.8801727294922 Accuracy: 0.5600000023841858
Loss: 200.61180114746094 Accuracy: 0.5800000429153442
Total Loss: 257.2261047363281 Total Accuracy: 0.5833333730697632
..........Saving the model..........
========= E

tensor([[ 2.2709, -1.8841]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3245.707773923874
Train steps: 33000, Loss: 0.015564516186714172
tensor([[-1.8327,  1.5231]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3284.111388683319
Train steps: 33500, Loss: 0.034286901354789734
========= Epoch 21 Testing =========
Loss: 125.61665344238281 Accuracy: 0.5299999713897705
Loss: 224.1562957763672 Accuracy: 0.5699999928474426
Loss: 326.9482116699219 Accuracy: 0.59333336353302
Total Loss: 421.00555419921875 Total Accuracy: 0.5885416865348816
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[-2.1328,  1.7104]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3354.5413954257965
Train steps: 34000, Loss: 0.021196968853473663
tensor([[-1.3626,  1.1901]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3392.2282185554504
Train steps: 34500, Loss: 0.07498566806316376
tensor([[-2.6366,  2.3144]], device='cuda:0', grad_fn=<AddmmBackwar

========= Epoch 31 Testing =========
Loss: 211.07855224609375 Accuracy: 0.6100000143051147
Loss: 508.7493591308594 Accuracy: 0.5849999785423279
Loss: 720.2023315429688 Accuracy: 0.6066666841506958
Total Loss: 905.7007446289062 Total Accuracy: 0.6067708730697632
..........Saving the model..........
========= Epoch 32 Training =========
tensor([[ 4.4968, -3.8844]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4900.356891155243
Train steps: 49500, Loss: 0.00022909401741344482
tensor([[ 4.6809, -4.0808]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4938.393998146057
Train steps: 50000, Loss: 0.00015662873920518905
tensor([[ 4.8060, -4.1714]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4981.397911310196
Train steps: 50500, Loss: 0.0001262346631847322
========= Epoch 32 Testing =========
Loss: 239.8597412109375 Accuracy: 0.6499999761581421
Loss: 473.2928466796875 Accuracy: 0.6449999809265137
Loss: 815.3222045898438 Accuracy: 0.6033333539962769
Total Loss: 101

tensor([[ 7.6672, -6.7206]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6437.981262683868
Train steps: 65000, Loss: 5.960462772236497e-07
tensor([[-7.9192,  6.9915]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6475.964497089386
Train steps: 65500, Loss: 3.576278118089249e-07
tensor([[ 8.0834, -7.0980]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6513.985974788666
Train steps: 66000, Loss: 2.3841855067985307e-07
========= Epoch 42 Testing =========
Loss: 576.8392944335938 Accuracy: 0.4699999988079071
Loss: 999.7095336914062 Accuracy: 0.5399999618530273
Loss: 1443.950927734375 Accuracy: 0.5566666722297668
Total Loss: 1783.72802734375 Total Accuracy: 0.5729166865348816
..........Saving the model..........
========= Epoch 43 Training =========
tensor([[-7.9502,  7.0294]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6581.356029510498
Train steps: 66500, Loss: 3.576278118089249e-07
tensor([[ 8.2902, -7.2919]], device='cuda:0', grad_fn=<AddmmBack

tensor([[ 9.8569, -9.3660]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8099.975556612015
Train steps: 82000, Loss: 0.0
tensor([[ 9.6900, -9.2828]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8142.504637956619
Train steps: 82500, Loss: 0.0
tensor([[-10.2143,   9.0698]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8189.16915345192
Train steps: 83000, Loss: 0.0
========= Epoch 53 Testing =========
Loss: 522.7050170898438 Accuracy: 0.5999999642372131
Loss: 1225.9791259765625 Accuracy: 0.5649999976158142
Loss: 1751.5692138671875 Accuracy: 0.5766666531562805
Total Loss: 2273.522705078125 Total Accuracy: 0.578125
..........Saving the model..........
========= Epoch 54 Training =========
tensor([[-10.2454,   9.0795]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8254.33153629303
Train steps: 83500, Loss: 0.0
tensor([[10.0491, -9.6414]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8293.413357496262
Train steps: 84000, Loss: 0.0
tensor([[-

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[ 0.0884, -0.1058]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 37.725356101989746
Train steps: 500, Loss: 0.7949539422988892
tensor([[ 0.0700, -0.1263]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 75.73775887489319
Train steps: 1000, Loss: 0.599817156791687
tensor([[ 0.0985, -0.1569]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 116.79134607315063
Train steps: 1500, Loss: 0.5735808610916138
========= Epoch 0 Testing =========
Loss: 69.30587768554688 Accuracy: 0.5299999713897705
Loss: 139.0843048095703 Accuracy: 0.5199999809265137
Loss: 206.46490478515625 Accuracy: 0.550000011920929
Total Loss: 264.6209716796875 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 0.0933, -0.1540]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 186.33784699440002
Train steps: 2000, Loss: 0.5770970582962036
tensor([[ 0.0899, -0.1520]], device='cuda:0', grad_fn=

Loss: 141.26239013671875 Accuracy: 0.4899999797344208
Loss: 208.83363342285156 Accuracy: 0.5266667008399963
Total Loss: 265.10150146484375 Total Accuracy: 0.5442708730697632
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[-0.0393, -0.1102]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1655.6651813983917
Train steps: 17000, Loss: 0.7292100191116333
tensor([[ 0.1798, -0.2062]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1693.5873563289642
Train steps: 17500, Loss: 0.9046828746795654
tensor([[ 0.1809, -0.2097]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1731.1109337806702
Train steps: 18000, Loss: 0.516823410987854
========= Epoch 11 Testing =========
Loss: 69.51727294921875 Accuracy: 0.5099999904632568
Loss: 139.63009643554688 Accuracy: 0.5249999761581421
Loss: 207.69949340820312 Accuracy: 0.5333333611488342
Total Loss: 264.6312255859375 Total Accuracy: 0.5442708730697632
..........Saving the model..........
========

tensor([[-1.4057,  1.0063]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3210.169895887375
Train steps: 33000, Loss: 0.08584585040807724
tensor([[ 2.5795, -2.2150]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3250.815751552582
Train steps: 33500, Loss: 0.008240981958806515
========= Epoch 21 Testing =========
Loss: 139.30787658691406 Accuracy: 0.550000011920929
Loss: 254.3258056640625 Accuracy: 0.5949999690055847
Loss: 378.36724853515625 Accuracy: 0.6000000238418579
Total Loss: 491.7502136230469 Total Accuracy: 0.5833333730697632
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[ 1.6152, -1.3115]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3316.582629919052
Train steps: 34000, Loss: 0.05219189450144768
tensor([[-1.4676,  0.9774]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3359.111561059952
Train steps: 34500, Loss: 0.08316978812217712
tensor([[-1.8803,  1.3364]], device='cuda:0', grad_fn=<AddmmBackward0>

========= Epoch 31 Testing =========
Loss: 269.2557373046875 Accuracy: 0.5699999928474426
Loss: 562.6583251953125 Accuracy: 0.5399999618530273
Loss: 865.877197265625 Accuracy: 0.5400000214576721
Total Loss: 1058.497314453125 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 32 Training =========
tensor([[-3.8357,  3.1287]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4826.947633504868
Train steps: 49500, Loss: 0.0009445258183404803
tensor([[ 4.5600, -4.1408]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4868.668126583099
Train steps: 50000, Loss: 0.00016640232934150845
tensor([[-4.0448,  3.2920]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4910.485990285873
Train steps: 50500, Loss: 0.0006509092636406422
========= Epoch 32 Testing =========
Loss: 307.52337646484375 Accuracy: 0.5299999713897705
Loss: 557.9320678710938 Accuracy: 0.5699999928474426
Loss: 850.8167114257812 Accuracy: 0.550000011920929
Total Loss: 1055.86584472656

tensor([[-5.3348,  4.5515]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6344.572911262512
Train steps: 65000, Loss: 5.090107151772827e-05
tensor([[-5.2642,  4.5521]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6383.229187011719
Train steps: 65500, Loss: 5.4596363042946905e-05
tensor([[-5.2990,  4.5110]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6422.910452604294
Train steps: 66000, Loss: 5.495397272170521e-05
========= Epoch 42 Testing =========
Loss: 341.6678771972656 Accuracy: 0.5600000023841858
Loss: 659.5340576171875 Accuracy: 0.5899999737739563
Loss: 1030.7779541015625 Accuracy: 0.5733333230018616
Total Loss: 1384.0762939453125 Total Accuracy: 0.5546875
..........Saving the model..........
========= Epoch 43 Training =========
tensor([[ 5.3600, -4.9892]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6487.46227812767
Train steps: 66500, Loss: 3.2066785934148356e-05
tensor([[-5.3329,  4.5549]], device='cuda:0', grad_fn=<AddmmBackward0>

tensor([[ 6.5474, -6.1626]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7940.967209815979
Train steps: 81500, Loss: 2.9802276912960224e-06
========= Epoch 52 Testing =========
Loss: 404.97442626953125 Accuracy: 0.5899999737739563
Loss: 958.66162109375 Accuracy: 0.550000011920929
Loss: 1530.2208251953125 Accuracy: 0.5366666913032532
Total Loss: 1816.7509765625 Total Accuracy: 0.5625
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[-6.5865,  5.7637]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8012.048580646515
Train steps: 82000, Loss: 4.291525328881107e-06
tensor([[ 6.9614, -6.5837]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8049.528327465057
Train steps: 82500, Loss: 1.3113011618770543e-06
tensor([[ 7.0048, -6.3344]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8090.783795833588
Train steps: 83000, Loss: 1.6689286894688848e-06
========= Epoch 53 Testing =========
Loss: 482.33392333984375 Accuracy: 0.59

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[ 0.3113, -0.2203]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 37.013262033462524
Train steps: 500, Loss: 0.9938753843307495
tensor([[ 0.1241, -0.0105]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 74.37463188171387
Train steps: 1000, Loss: 0.6281057596206665
tensor([[ 0.1255, -0.0168]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 112.11656165122986
Train steps: 1500, Loss: 0.6245316863059998
========= Epoch 0 Testing =========
Loss: 68.477294921875 Accuracy: 0.5799999833106995
Loss: 138.187255859375 Accuracy: 0.5399999618530273
Loss: 207.03717041015625 Accuracy: 0.5400000214576721
Total Loss: 264.7351379394531 Total Accuracy: 0.546875
..........Saving the model..........
========= Epoch 1 Training =========
tensor([[ 0.1399, -0.0030]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 179.53709888458252
Train steps: 2000, Loss: 0.7671231627464294
tensor([[ 0.1148, -0.0145]], device='cuda:0', grad_fn=<

Loss: 140.62506103515625 Accuracy: 0.5299999713897705
Loss: 209.89512634277344 Accuracy: 0.5200000405311584
Total Loss: 270.6529235839844 Total Accuracy: 0.5130208730697632
..........Saving the model..........
========= Epoch 11 Training =========
tensor([[ 0.2519, -0.1794]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1639.9407107830048
Train steps: 17000, Loss: 0.5005897879600525
tensor([[-0.0065,  0.1097]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1678.3407003879547
Train steps: 17500, Loss: 0.752936601638794
tensor([[-0.3190,  0.4510]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1720.0327537059784
Train steps: 18000, Loss: 0.380513459444046
========= Epoch 11 Testing =========
Loss: 73.94384002685547 Accuracy: 0.47999998927116394
Loss: 145.42922973632812 Accuracy: 0.4899999797344208
Loss: 217.91885375976562 Accuracy: 0.5066666603088379
Total Loss: 275.7519836425781 Total Accuracy: 0.5130208730697632
..........Saving the model..........
=========

tensor([[ 1.0124, -1.2144]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3179.128722667694
Train steps: 33000, Loss: 0.1024341806769371
tensor([[-1.5432,  1.7340]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3219.331037759781
Train steps: 33500, Loss: 0.03704078495502472
========= Epoch 21 Testing =========
Loss: 138.3801727294922 Accuracy: 0.4699999988079071
Loss: 267.5791320800781 Accuracy: 0.48499998450279236
Loss: 415.4445495605469 Accuracy: 0.4766666889190674
Total Loss: 536.107177734375 Total Accuracy: 0.4817708432674408
..........Saving the model..........
========= Epoch 22 Training =========
tensor([[ 0.6802, -0.8922]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3284.8423902988434
Train steps: 34000, Loss: 0.1885945349931717
tensor([[-1.9413,  2.1721]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3322.4380156993866
Train steps: 34500, Loss: 0.01621991954743862
tensor([[-2.2077,  2.6138]], device='cuda:0', grad_fn=<AddmmBackward0>)


========= Epoch 31 Testing =========
Loss: 261.4878234863281 Accuracy: 0.5299999713897705
Loss: 533.369140625 Accuracy: 0.5
Loss: 819.2831420898438 Accuracy: 0.4933333396911621
Total Loss: 1032.9173583984375 Total Accuracy: 0.4973958432674408
..........Saving the model..........
========= Epoch 32 Training =========
tensor([[ 2.6498, -3.2481]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4753.091711997986
Train steps: 49500, Loss: 0.0027416283264756203
tensor([[ 3.0321, -3.6331]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4796.966228961945
Train steps: 50000, Loss: 0.0012736550997942686
tensor([[-2.5870,  2.9034]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4838.753748416901
Train steps: 50500, Loss: 0.004117939155548811
========= Epoch 32 Testing =========
Loss: 258.3160400390625 Accuracy: 0.5299999713897705
Loss: 575.9376220703125 Accuracy: 0.4749999940395355
Loss: 872.826904296875 Accuracy: 0.47333335876464844
Total Loss: 1106.8265380859375 Total 

tensor([[ 4.7422, -5.3432]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6233.800319433212
Train steps: 65000, Loss: 4.172238186583854e-05
tensor([[-5.0839,  5.6080]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6274.927527189255
Train steps: 65500, Loss: 2.276871418871451e-05
tensor([[-5.1566,  5.5732]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6314.439132928848
Train steps: 66000, Loss: 2.1934269170742482e-05
========= Epoch 42 Testing =========
Loss: 448.1402282714844 Accuracy: 0.4899999797344208
Loss: 832.1139526367188 Accuracy: 0.5049999952316284
Loss: 1323.53076171875 Accuracy: 0.4766666889190674
Total Loss: 1729.7828369140625 Total Accuracy: 0.4609375
..........Saving the model..........
========= Epoch 43 Training =========
tensor([[-5.2638,  5.7655]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6383.598109006882
Train steps: 66500, Loss: 1.6212332411669195e-05
tensor([[ 5.1988, -5.8107]], device='cuda:0', grad_fn=<AddmmBackward0>)

tensor([[-7.7322,  8.1430]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7789.29465341568
Train steps: 81500, Loss: 1.1920927533992653e-07
========= Epoch 52 Testing =========
Loss: 794.491455078125 Accuracy: 0.4599999785423279
Loss: 1522.1475830078125 Accuracy: 0.4699999988079071
Loss: 2189.5791015625 Accuracy: 0.4866666793823242
Total Loss: 2785.129638671875 Total Accuracy: 0.4791666865348816
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[ 7.4103, -7.9310]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7856.172279834747
Train steps: 82000, Loss: 2.3841855067985307e-07
tensor([[ 7.8025, -8.3286]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7894.9607610702515
Train steps: 82500, Loss: 1.1920928244535389e-07
tensor([[ 7.6639, -8.1630]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7932.413758277893
Train steps: 83000, Loss: 1.1920928244535389e-07
========= Epoch 53 Testing =========
Loss: 669.3107299804688 A