In [1]:
import torch
import torchvision
# from torch.utils.tensorboard import SummaryWriter
import time
from torch import nn
from torch.utils.data import DataLoader
from load_data import MyData  # self-made
from torchvision import transforms
from tqdm import tqdm_notebook as tqdm # View procedure
import os
import scipy.io
from random import random
import numpy as np
import gc
from torch.utils.tensorboard import SummaryWriter
from net_cnn_lstm1 import MyNetwork
from torchnlp.word_to_vector import GloVe
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [2]:
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ random
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ optimizer
import torch.optim as optim
device = torch.device("cuda:0")
gc.collect()
torch.cuda.empty_cache()
# ==损失函数权重
# ======== 二分类HC/DOC
# 计算总样本数量
# condition1
# total_samples = 887 + 985 + 879
# condition2
# total_samples = 929 + 1029 + 886
# condition3
# total_samples = 887 + 975 + 879
# rest
total_samples = 852 + 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 887, total_samples / (985 + 879)]
# condition2
# weights = [total_samples / 929, total_samples / (1029 + 886)]
# condition3
weights = [total_samples / 852, total_samples / (1051 + 872)]

# ======== 二分类MCS/UWS
# 计算总样本数量
# condition1
# total_samples = 985 + 879
# condition2
# total_samples = 1029 + 886
# condition3
# total_samples = 975 + 879
# rest
# total_samples = 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 985, total_samples / 879]
# condition2
# weights = [total_samples / 1029, total_samples / 886]
# condition3
# weights = [total_samples / 975, total_samples / 879]
# condition3
# weights = [total_samples / 1051, total_samples / 872]
# 将权重转换为张量
weights_tensor = torch.tensor(weights, device=device)

# 定义交叉熵损失函数并设置权重
criterion = nn.CrossEntropyLoss(weight=weights_tensor)
# criterion = nn.CrossEntropyLoss()
criterion = criterion.to(device)

In [3]:
def make_dataset(dataset,mode):
    # find the fold file
    count = 0
    for person in range(len(dataset)):
        filename = os.path.join(dataset.path, dataset.file_path[person])
        # extract the pure name of the file
        parts = filename.split("\\")
        file_name = parts[-1]
        name_without_extension = file_name.split(".")[0]
        # label or data
        file_last = name_without_extension.split("_")[-1]
        if file_last.isdigit(): # data
            # is this fold or not
            if int(file_last) == fold: # yes
                print(filename)
                count = count + 1
                data_map = torch.load(filename)
                # train or test
                if name_without_extension.split("_")[-2] == "train":
                    for i in range(data_map.size(0)):
                        train_data.append(data_map[i])
                elif name_without_extension.split("_")[-2] == "test":
                    for i in range(data_map.size(0)):
                        test_data.append(data_map[i])
                if count == 4:
                    del data_map
                    gc.collect()
                    torch.cuda.empty_cache() 
                    break
            else:   # not
                pass
        else: # label
            file_last = name_without_extension.split("_")[-4]
            file_mode = name_without_extension.split("_")[-2]
            if file_mode == mode.split("_")[-1]: # is this mode or not
                # is this fold or not
                if int(file_last) == fold: # yes
                    print(filename)
                    count = count + 1
                    data_map = torch.load(filename)
                    # train or test
                    if name_without_extension.split("_")[-5] == "train":
                        for i in range(data_map.size(0)):
                            train_label.append(data_map[i])
                    elif name_without_extension.split("_")[-5] == "test":
                        for i in range(data_map.size(0)):
                            test_label.append(data_map[i])
                    if count == 4:
                        del data_map
                        gc.collect()
                        torch.cuda.empty_cache() 
                        break
                else:   # not
                    pass
            else:
                pass
        del filename, parts, file_name, name_without_extension, file_last
        gc.collect()
        torch.cuda.empty_cache()    
# 定义LSTM超参数
input_size = 64  # 输入特征维度
# hidden_size = 64  # 隐藏单元数量
# input_size = 59  # 输入特征维度
hidden_size = 64  # 隐藏单元数量
num_layers = 2  # LSTM层数
output_size = 2  # 输出类别数量
# 创建模型实例
# model_list = ['', '_CNN', '_CNN_spa', '_CNN_spa_lstm']
# model_name = model_list[0]
# if model_name == model_list[0]: #  CascadeCept
#     from network_cnn_lstm import MyNetwork
# elif model_name == model_list[1]: #  CNN
#     from network_cnn_lstm_2 import MyNetwork
# elif model_name == model_list[2]: # CascadeCept_1
#     from network_cnn_lstm_3 import MyNetwork
# elif model_name == model_list[3]: # CascadeCept_2
#     from network_cnn_lstm_4 import MyNetwork
model_list = ['_1', '_2', '_3', '_4','_5','_6','_7','_8','_9','_10','_11']
model_name = model_list[0]
if model_name == model_list[0]: 
    from net_cnn_lstm1 import MyNetwork
elif model_name == model_list[1]: 
    from net_cnn_lstm2 import MyNetwork
elif model_name == model_list[2]: 
    from net_cnn_lstm3 import MyNetwork
elif model_name == model_list[3]: 
    from net_cnn_lstm4 import MyNetwork
elif model_name == model_list[4]: 
    from net_cnn_lstm5 import MyNetwork
elif model_name == model_list[5]: 
    from net_cnn_lstm6 import MyNetwork
elif model_name == model_list[6]: 
    from net_cnn_lstm7 import MyNetwork
elif model_name == model_list[7]: 
    from net_cnn_lstm8 import MyNetwork
elif model_name == model_list[8]: 
    from net_cnn_lstm9 import MyNetwork
elif model_name == model_list[9]: 
    from net_cnn_lstm10 import MyNetwork
elif model_name == model_list[10]: 
    from net_cnn_lstm11 import MyNetwork
model = MyNetwork(input_size, hidden_size, num_layers, output_size)
model = model.to(device)

# experimental dir: rest, conditionA, conditionB, conditionC
exper_dir = "condition1"
# ————————————————————————————————————————check this for every run!!!!!!!!!!!!!!!!
# trial="_1"
trial = ''
# root_dir = f"../data/eegmap_split/{exper_dir}"
root_dir = f"../data/eegmap_split/{exper_dir}"
# classification = "hc_doc"/doc or "mcs_uws"/uws
classification = "hc_doc"
# classification = "mcs_uws"
fold_num = 5
best_val_loss = float('inf')
for fold in tqdm(range(5)):
    # train num folds
#     fold = 0 # 选择折数
    # -- prepare datasets
    train_data = []
    train_label = []
    test_data = []
    test_label = []
    
    if classification == "hc_doc":
        # ---- hc
        dataset = MyData(root_dir, "train", "hc") # hc
        make_dataset(dataset,classification)
        dataset = MyData(root_dir, "test", "hc") # hc
        make_dataset(dataset,classification)
    # ---- mcs
    dataset = MyData(root_dir, "train", "mcs") # mcs
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "mcs") # hc
    make_dataset(dataset,classification)
    # ---- uws
    dataset = MyData(root_dir, "train", "uws") # uws
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "uws") # hc
    make_dataset(dataset,classification)
    
    print(torch.stack(train_data).size())
    print(torch.stack(train_label).size())
    print(torch.stack(test_data).size())
    print(torch.stack(test_label).size())
    del dataset
    gc.collect()
    torch.cuda.empty_cache()  
    
    train_data = torch.stack(train_data)
    train_label = torch.stack(train_label)
    test_data = torch.stack(test_data)
    test_label = torch.stack(test_label)
    # train dataset
    train_td = TensorDataset(train_data, train_label)
    train_loader = DataLoader(train_td, batch_size = BATCH_SIZE, shuffle = True)
    # test dataset
    test_td = TensorDataset(test_data, test_label)
    test_loader = DataLoader(test_td, batch_size = BATCH_SIZE, shuffle = True)
    del train_data, train_label, test_data, test_label, train_td, test_td
    gc.collect()
    torch.cuda.empty_cache()
    
    # set model for each fold
    model = MyNetwork(input_size, hidden_size, num_layers, output_size)
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr = learn_rate)
    scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 30, 50], gamma=0.2)
#     scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5, verbose=True)
    # -- start training
    start_time = time.time()
    # train and test step records
    total_train_step = 0
    total_test_step = 0
    min_test_loss = 1000
    # add Tensorboard
#     writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_train_{fold}")
#     writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_{fold}")
#     writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_acc_{fold}")
    writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_train_{fold}")
    writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_{fold}")
    writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_acc_{fold}")
    for i in tqdm(range(num_epochs)):  
        print(f"========= Epoch {i} Training =========")
        # train steps
        model.train()
        for data in train_loader:
            # x, y
            data_map, label=data
            data_map_reshaped = torch.reshape(data_map, (110, 1, 1, 2400))
#             data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
            label_int = label.long()
            data_map_reshaped=data_map_reshaped.to(device)
            label_int=label_int.to(device)
            del data_map, label
            gc.collect()
            torch.cuda.empty_cache()
            # y_pred
            label_pred = model(data_map_reshaped)
            # Loss Computation and Optimization
            loss = criterion(label_pred,label_int)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            # draw tensorboard
            total_train_step = total_train_step + 1
            # print info
            if total_train_step % 500 == 0:
                end_time = time.time()
                print(label_pred)
                print(f"Train time: {end_time - start_time}")
                print(f"Train steps: {total_train_step}, Loss: {loss.item()}")
            writer_train.add_scalar("train_loss",loss.item(),total_train_step)
            # Clear gpu
            del data, data_map_reshaped, label_int, label_pred, loss
            gc.collect()
            torch.cuda.empty_cache()
        
        # Evaluation and save the best model
        print(f"========= Epoch {i} Testing =========")
        model.eval()
        test_loss = 0
        total_test_loss = 0
        test_count = 0
        total_test_acc = 0
        with torch.no_grad():
            for data in test_loader:
                test_count = test_count + 1
                # x, y
                data_map, label=data
                data_map_reshaped = torch.reshape(data_map, (110, 1, 1, 2400))
#                 data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
                label_int = label.long()
                data_map_reshaped = data_map_reshaped.to(device)
                label_int = label_int.to(device)
                del data_map, label
                gc.collect()
                torch.cuda.empty_cache()
                # y_pred
                label_pred_test = model(data_map_reshaped)
                loss = criterion(label_pred_test,label_int)
#                 print(label_pred_test)
                # accuracy 
                total_test_acc = total_test_acc + ((label_pred_test.argmax(1)) == label_int).sum()
                # change lr
                test_loss += loss.item()
                test_loss /= len(test_loader)
                if test_loss < best_val_loss:
                    best_val_loss = test_loss
                scheduler.step()
                # draw tensorboad
                total_test_loss = total_test_loss + loss
                if test_count % 100 == 0:
                    print(f"Loss: {total_test_loss} Accuracy: {total_test_acc/test_count}")
                # Clear gpu
                del data_map_reshaped, label_int, label_pred_test, loss, data
                gc.collect()
                torch.cuda.empty_cache()
        print(f"Total Loss: {total_test_loss} Total Accuracy: {total_test_acc/test_count}")
        writer_valid.add_scalar("test_loss", total_test_loss, total_test_step)
        writer_valid_acc.add_scalar("test_acc", total_test_acc/test_count, total_test_step)
        total_test_step = total_test_step + 1
        print("..........Saving the model..........")
#         torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}/Fold{fold}_Epoch{i}.pt") 
        torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}{trial}/Fold{fold}_Epoch{i}.pt") 
#         if total_test_loss < min_test_loss:
#             min_test_loss = total_test_loss
#             print("..........Saving the model..........")
#             torch.save(model.state_dict(),f"../model/{exper_dir}/Fold{fold}_Epoch{i}.pt")

D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:117: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/5 [00:00<?, ?it/s]

../data/eegmap_split/condition1\train\hc\condition1_hc_train_0.pt
../data/eegmap_split/condition1\train\hc\condition1_hc_train_0_hc_doc_label.pt
../data/eegmap_split/condition1\test\hc\condition1_hc_test_0.pt
../data/eegmap_split/condition1\test\hc\condition1_hc_test_0_hc_doc_label.pt
../data/eegmap_split/condition1\train\mcs\condition1_mcs_train_0.pt
../data/eegmap_split/condition1\train\mcs\condition1_mcs_train_0_hc_doc_label.pt
../data/eegmap_split/condition1\test\mcs\condition1_mcs_test_0.pt
../data/eegmap_split/condition1\test\mcs\condition1_mcs_test_0_hc_doc_label.pt
../data/eegmap_split/condition1\train\uws\condition1_uws_train_0.pt
../data/eegmap_split/condition1\train\uws\condition1_uws_train_0_hc_doc_label.pt
../data/eegmap_split/condition1\test\uws\condition1_uws_test_0.pt
../data/eegmap_split/condition1\test\uws\condition1_uws_test_0_hc_doc_label.pt
torch.Size([3055, 2400, 10, 11])
torch.Size([3055])
torch.Size([762, 2400, 10, 11])
torch.Size([762])


D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:184: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.4559,  0.3817]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 45.05323791503906
Train steps: 500, Loss: 0.35960400104522705
tensor([[-0.0356,  0.0317]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 86.11304998397827
Train steps: 1000, Loss: 0.7273816466331482
tensor([[-0.0501, -0.0653]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 127.01842331886292
Train steps: 1500, Loss: 0.6855891942977905
tensor([[ 0.0381, -0.1834]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 168.0402340888977
Train steps: 2000, Loss: 0.8100376725196838
tensor([[ 0.1666, -0.3442]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 208.9452953338623
Train steps: 2500, Loss: 0.9808361530303955
tensor([[-0.3809,  0.5883]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 249.86233401298523
Train steps: 3000, Loss: 0.321653813123703
========= Epoch 0 Testing =========
Loss: 63.71345901489258 Accuracy: 0.66999995708465

Loss: 123.03253936767578 Accuracy: 0.8400000333786011
Loss: 163.47970581054688 Accuracy: 0.8374999761581421
Loss: 197.45437622070312 Accuracy: 0.8500000238418579
Loss: 235.62759399414062 Accuracy: 0.8483333587646484
Loss: 271.9991760253906 Accuracy: 0.8471428751945496
Total Loss: 295.9372863769531 Total Accuracy: 0.847769021987915
..........Saving the model..........
========= Epoch 6 Training =========
tensor([[ 0.8779, -0.3479]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1863.4475617408752
Train steps: 18500, Loss: 0.25735417008399963
tensor([[-0.0546,  0.4384]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1904.1027479171753
Train steps: 19000, Loss: 0.4767538905143738
tensor([[-1.0868,  1.3959]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1945.2838423252106
Train steps: 19500, Loss: 0.08021295815706253
tensor([[ 0.7259, -0.3265]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1986.2751908302307
Train steps: 20000, Loss: 0.2994272708892822

tensor([[-1.3222,  1.7354]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3577.2921557426453
Train steps: 36000, Loss: 0.045929208397865295
tensor([[-1.3330,  1.7682]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3617.832091331482
Train steps: 36500, Loss: 0.04400885850191116
========= Epoch 11 Testing =========
Loss: 36.08963394165039 Accuracy: 0.85999995470047
Loss: 72.9625015258789 Accuracy: 0.8399999737739563
Loss: 94.4422607421875 Accuracy: 0.8700000047683716
Loss: 132.2308807373047 Accuracy: 0.8700000047683716
Loss: 170.52322387695312 Accuracy: 0.8680000305175781
Loss: 210.11038208007812 Accuracy: 0.8666666746139526
Loss: 243.81764221191406 Accuracy: 0.8657142519950867
Total Loss: 264.123291015625 Total Accuracy: 0.8661417365074158
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[-1.3781,  1.8014]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3715.3923881053925
Train steps: 37000, Loss: 0.04076221585273743
tensor(

tensor([[-1.4137,  1.8447]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5694.097692012787
Train steps: 53000, Loss: 0.03773036599159241
tensor([[ 1.4538, -0.8730]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5745.797424316406
Train steps: 53500, Loss: 0.09313084930181503
tensor([[ 1.2138, -0.7383]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5801.226159572601
Train steps: 54000, Loss: 0.13276030123233795
tensor([[ 1.6517, -1.0450]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5856.201675415039
Train steps: 54500, Loss: 0.06525100767612457
========= Epoch 17 Testing =========
Loss: 38.92757797241211 Accuracy: 0.8499999642372131
Loss: 69.15474700927734 Accuracy: 0.85999995470047
Loss: 103.77754211425781 Accuracy: 0.8500000238418579
Loss: 139.4970245361328 Accuracy: 0.8524999618530273
Loss: 174.80014038085938 Accuracy: 0.8580000400543213
Loss: 206.50494384765625 Accuracy: 0.8616666793823242
Loss: 233.21473693847656 Accuracy: 0.868571400642395

Loss: 191.3993682861328 Accuracy: 0.8766666650772095
Loss: 216.5161895751953 Accuracy: 0.8771428465843201
Total Loss: 238.69081115722656 Total Accuracy: 0.874015748500824
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-1.1196,  1.6431]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7974.909620285034
Train steps: 70500, Loss: 0.06120798736810684
tensor([[-1.6319,  2.1512]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8029.394964694977
Train steps: 71000, Loss: 0.02249777875840664
tensor([[ 1.2362, -0.7322]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8082.931829452515
Train steps: 71500, Loss: 0.13074441254138947
tensor([[-1.7084,  2.2118]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8138.821900844574
Train steps: 72000, Loss: 0.019642364233732224
tensor([[-1.5760,  2.0932]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8193.829226255417
Train steps: 72500, Loss: 0.025176752358675003
tensor([[-1.

tensor([[-1.8712,  2.3955]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10201.339701414108
Train steps: 88500, Loss: 4.280636787414551
========= Epoch 28 Testing =========
Loss: 31.538898468017578 Accuracy: 0.8700000047683716
Loss: 59.26919174194336 Accuracy: 0.875
Loss: 89.06407928466797 Accuracy: 0.8733333349227905
Loss: 119.0581283569336 Accuracy: 0.8700000047683716
Loss: 143.4576873779297 Accuracy: 0.878000020980835
Loss: 170.2432098388672 Accuracy: 0.8816666603088379
Loss: 195.00352478027344 Accuracy: 0.8828571438789368
Total Loss: 216.39749145507812 Total Accuracy: 0.883202075958252
..........Saving the model..........
========= Epoch 29 Training =========
tensor([[-1.7885,  2.3372]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10316.708310842514
Train steps: 89000, Loss: 0.016024257987737656
tensor([[-0.5237,  1.0304]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10370.10856461525
Train steps: 89500, Loss: 0.19176927208900452
tensor([[ 1.6658, -

tensor([[ 1.7208, -1.1491]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12359.264025449753
Train steps: 105000, Loss: 0.05515489727258682
tensor([[ 2.2830, -1.6625]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12413.301253080368
Train steps: 105500, Loss: 0.01915680058300495
tensor([[-2.1162,  2.7198]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12468.252764463425
Train steps: 106000, Loss: 0.007907632738351822
tensor([[ 1.9134, -1.3812]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12516.180239915848
Train steps: 106500, Loss: 0.03641222417354584
========= Epoch 34 Testing =========
Loss: 25.475360870361328 Accuracy: 0.8799999952316284
Loss: 48.199642181396484 Accuracy: 0.8949999809265137
Loss: 75.81874084472656 Accuracy: 0.8866667151451111
Loss: 105.73834991455078 Accuracy: 0.887499988079071
Loss: 137.3977508544922 Accuracy: 0.8840000629425049
Loss: 169.29930114746094 Accuracy: 0.8816666603088379
Loss: 205.18984985351562 Accuracy: 0.8771

Loss: 119.5428237915039 Accuracy: 0.887499988079071
Loss: 141.1460418701172 Accuracy: 0.8920000195503235
Loss: 168.9068603515625 Accuracy: 0.8883333802223206
Loss: 210.7830810546875 Accuracy: 0.8799999952316284
Total Loss: 231.34344482421875 Total Accuracy: 0.8779527544975281
..........Saving the model..........
========= Epoch 40 Training =========
tensor([[-2.0077,  2.5862]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14626.281130313873
Train steps: 122500, Loss: 0.010062796995043755
tensor([[-2.6802,  3.3559]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14677.477259874344
Train steps: 123000, Loss: 0.002388007938861847
tensor([[-2.5879,  3.2691]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14733.970902204514
Train steps: 123500, Loss: 0.0028556303586810827
tensor([[-2.5252,  3.2283]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 14787.606979131699
Train steps: 124000, Loss: 0.0031666632276028395
tensor([[ 2.5443, -1.9096]], device='cuda:

tensor([[-2.8150,  3.5484]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16794.056125879288
Train steps: 139500, Loss: 0.0017219253350049257
tensor([[ 2.6903, -2.1117]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16850.105592012405
Train steps: 140000, Loss: 0.008179736323654652
tensor([[-2.9885,  3.6911]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16905.947701454163
Train steps: 140500, Loss: 0.0012554391287267208
========= Epoch 45 Testing =========
Loss: 31.31204605102539 Accuracy: 0.8700000047683716
Loss: 84.38092803955078 Accuracy: 0.85999995470047
Loss: 115.5376205444336 Accuracy: 0.8700000047683716
Loss: 143.67962646484375 Accuracy: 0.8774999976158142
Loss: 184.7065887451172 Accuracy: 0.878000020980835
Loss: 216.3728485107422 Accuracy: 0.878333330154419
Loss: 255.85227966308594 Accuracy: 0.8799999952316284
Total Loss: 274.30279541015625 Total Accuracy: 0.8805774450302124
..........Saving the model..........
========= Epoch 46 Training ========

tensor([[ 2.9254, -2.3077]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18973.868011713028
Train steps: 156000, Loss: 0.005323163699358702
tensor([[ 2.9598, -2.3752]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19029.362616300583
Train steps: 156500, Loss: 0.004808410070836544
tensor([[-3.1877,  3.9206]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19084.17940711975
Train steps: 157000, Loss: 0.0008179179858416319
tensor([[ 3.0207, -2.4208]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19139.56979417801
Train steps: 157500, Loss: 0.004323658533394337
tensor([[ 2.6950, -2.1261]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19195.348046302795
Train steps: 158000, Loss: 0.008025423623621464
tensor([[ 3.1160, -2.5062]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19251.04402089119
Train steps: 158500, Loss: 0.0036104037426412106
========= Epoch 51 Testing =========
Loss: 49.2144775390625 Accuracy: 0.8700000047683716
Loss: 

========= Epoch 56 Testing =========
Loss: 45.16351318359375 Accuracy: 0.8799999952316284
Loss: 81.71430969238281 Accuracy: 0.8999999761581421
Loss: 130.61376953125 Accuracy: 0.8966667056083679
Loss: 203.6842498779297 Accuracy: 0.8774999976158142
Loss: 241.67477416992188 Accuracy: 0.8840000629425049
Loss: 257.0148010253906 Accuracy: 0.893333375453949
Loss: 306.9561767578125 Accuracy: 0.8899999856948853
Total Loss: 318.5490417480469 Total Accuracy: 0.8950130939483643
..........Saving the model..........
========= Epoch 57 Training =========
tensor([[-3.5418,  4.2663]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 21371.765691518784
Train steps: 174500, Loss: 0.000406301929615438
tensor([[-3.5708,  4.3028]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 21426.062407016754
Train steps: 175000, Loss: 0.00038056288030929863
tensor([[-2.8993,  3.5607]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 21481.437698841095
Train steps: 175500, Loss: 0.001563637168146669

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.1484,  0.3055]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 52.69654154777527
Train steps: 500, Loss: 0.9456356763839722
tensor([[-0.3176,  0.4660]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 106.20613813400269
Train steps: 1000, Loss: 0.37620705366134644
tensor([[-0.6733,  0.6099]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 161.03677368164062
Train steps: 1500, Loss: 0.24463078379631042
tensor([[-0.2677,  0.2085]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 216.35261726379395
Train steps: 2000, Loss: 0.4831228256225586
tensor([[-0.7829,  0.8168]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 271.5707688331604
Train steps: 2500, Loss: 0.1839546263217926
tensor([[-0.0751,  0.2375]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 326.42896842956543
Train steps: 3000, Loss: 0.5490176677703857
========= Epoch 0 Testing =========
Loss: 53.51079559326172 Accuracy: 0.7799999713

Loss: 93.92791748046875 Accuracy: 0.8766666650772095
Loss: 124.74681091308594 Accuracy: 0.8774999976158142
Loss: 155.6417236328125 Accuracy: 0.8760000467300415
Loss: 186.5161895751953 Accuracy: 0.8733333349227905
Loss: 222.90756225585938 Accuracy: 0.8700000047683716
Total Loss: 239.87234497070312 Total Accuracy: 0.8700787425041199
..........Saving the model..........
========= Epoch 6 Training =========
tensor([[-1.5489,  1.6853]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2349.817929983139
Train steps: 18500, Loss: 0.03863431513309479
tensor([[-1.9207,  2.0227]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2404.588520050049
Train steps: 19000, Loss: 0.01919621042907238
tensor([[-1.7754,  1.8960]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2458.5365555286407
Train steps: 19500, Loss: 0.025122929364442825
tensor([[ 1.0081, -0.8263]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2512.2405622005463
Train steps: 20000, Loss: 0.1481721699237823

tensor([[ 1.2323, -1.0648]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4537.920008897781
Train steps: 36000, Loss: 0.09580641984939575
tensor([[-2.4566,  2.4466]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4590.902446985245
Train steps: 36500, Loss: 0.007395628374069929
========= Epoch 11 Testing =========
Loss: 31.264251708984375 Accuracy: 0.7999999523162842
Loss: 51.265472412109375 Accuracy: 0.8499999642372131
Loss: 74.63212585449219 Accuracy: 0.8600000143051147
Loss: 110.28744506835938 Accuracy: 0.8574999570846558
Loss: 140.52777099609375 Accuracy: 0.8560000658035278
Loss: 168.69676208496094 Accuracy: 0.8533333539962769
Loss: 194.44354248046875 Accuracy: 0.8585714101791382
Total Loss: 218.55670166015625 Total Accuracy: 0.8503937125205994
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[-2.0644,  2.2344]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4701.798875808716
Train steps: 37000, Loss: 0.013493993319571018

tensor([[-3.3037,  3.3712]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6728.410564184189
Train steps: 53000, Loss: 0.0012613920262083411
tensor([[ 1.4085, -1.2015]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6783.5188591480255
Train steps: 53500, Loss: 0.07095935195684433
tensor([[ 1.0082, -0.8582]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6837.945192575455
Train steps: 54000, Loss: 0.14382274448871613
tensor([[-2.5357,  2.8813]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6891.6428871154785
Train steps: 54500, Loss: 0.004430478438735008
========= Epoch 17 Testing =========
Loss: 32.06140899658203 Accuracy: 0.8700000047683716
Loss: 59.6919059753418 Accuracy: 0.8700000047683716
Loss: 83.53189086914062 Accuracy: 0.8766666650772095
Loss: 104.59396362304688 Accuracy: 0.8899999856948853
Loss: 129.30239868164062 Accuracy: 0.89000004529953
Loss: 158.41070556640625 Accuracy: 0.8850000500679016
Loss: 189.88580322265625 Accuracy: 0.88285714387

Loss: 137.15963745117188 Accuracy: 0.8840000629425049
Loss: 165.6466064453125 Accuracy: 0.8866667151451111
Loss: 195.91026306152344 Accuracy: 0.8871428370475769
Total Loss: 217.51190185546875 Total Accuracy: 0.8858267664909363
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-3.9134,  4.1228]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8974.358188152313
Train steps: 70500, Loss: 0.0003234816831536591
tensor([[ 0.8800, -0.7277]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9028.637350082397
Train steps: 71000, Loss: 0.18261203169822693
tensor([[ 2.2032, -2.0072]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9082.767883300781
Train steps: 71500, Loss: 0.014731441624462605
tensor([[-3.8931,  4.1023]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9137.77140545845
Train steps: 72000, Loss: 0.0003369478799868375
tensor([[-4.0672,  4.1875]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9193.820866823196


tensor([[-3.9483,  4.1991]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11161.321688890457
Train steps: 88000, Loss: 0.00028951745480298996
tensor([[-4.4098,  4.6307]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11216.123608112335
Train steps: 88500, Loss: 0.00011848701251437888
========= Epoch 28 Testing =========
Loss: 30.269577026367188 Accuracy: 0.8799999952316284
Loss: 57.91522216796875 Accuracy: 0.8949999809265137
Loss: 100.3058090209961 Accuracy: 0.8866667151451111
Loss: 138.9097137451172 Accuracy: 0.8824999928474426
Loss: 172.2987518310547 Accuracy: 0.8920000195503235
Loss: 189.34609985351562 Accuracy: 0.8983333706855774
Loss: 223.8907470703125 Accuracy: 0.8985714316368103
Total Loss: 231.48683166503906 Total Accuracy: 0.904199481010437
..........Saving the model..........
========= Epoch 29 Training =========
tensor([[-3.4891,  3.7782]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11327.624197721481
Train steps: 89000, Loss: 0.000697726965881

tensor([[-4.6502,  4.7306]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13298.316439628601
Train steps: 104500, Loss: 8.427741704508662e-05
tensor([[ 2.6918, -2.5458]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13353.092883825302
Train steps: 105000, Loss: 0.005298737436532974
tensor([[ 2.8789, -2.5745]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13408.994354248047
Train steps: 105500, Loss: 0.004272737540304661
tensor([[ 2.1183, -1.7913]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13462.882440567017
Train steps: 106000, Loss: 0.019850758835673332
tensor([[ 2.4762, -2.1510]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13516.789360523224
Train steps: 106500, Loss: 0.009734068997204304
========= Epoch 34 Testing =========
Loss: 51.64956283569336 Accuracy: 0.8799999952316284
Loss: 89.74234771728516 Accuracy: 0.8949999809265137
Loss: 114.61149597167969 Accuracy: 0.9066666960716248
Loss: 129.629150390625 Accuracy: 0.919999957084

========= Epoch 39 Testing =========
Loss: 24.09735107421875 Accuracy: 0.9399999976158142
Loss: 76.97904205322266 Accuracy: 0.9149999618530273
Loss: 107.09881591796875 Accuracy: 0.9100000262260437
Loss: 167.8172607421875 Accuracy: 0.9024999737739563
Loss: 207.73069763183594 Accuracy: 0.9040000438690186
Loss: 251.94532775878906 Accuracy: 0.9033333659172058
Loss: 266.259033203125 Accuracy: 0.9114285707473755
Total Loss: 283.35223388671875 Total Accuracy: 0.913385808467865
..........Saving the model..........
========= Epoch 40 Training =========
tensor([[-5.1498,  5.4094]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15602.41039800644
Train steps: 122500, Loss: 2.5987286790041253e-05
tensor([[-3.6926,  4.1821]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15656.274827003479
Train steps: 123000, Loss: 0.00038020533975213766
tensor([[-4.9932,  5.2378]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15710.387645483017
Train steps: 123500, Loss: 3.6000557884108

tensor([[ 4.0807, -3.8593]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17673.942885160446
Train steps: 139000, Loss: 0.00035613393993116915
tensor([[-5.4591,  5.6960]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17729.02087020874
Train steps: 139500, Loss: 1.4305012882687151e-05
tensor([[-4.2076,  4.3093]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17783.567121505737
Train steps: 140000, Loss: 0.00020001317898277193
tensor([[-5.3194,  5.7694]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17836.66136431694
Train steps: 140500, Loss: 1.5258672647178173e-05
========= Epoch 45 Testing =========
Loss: 66.30787658691406 Accuracy: 0.8899999856948853
Loss: 115.06472778320312 Accuracy: 0.8999999761581421
Loss: 175.22567749023438 Accuracy: 0.893333375453949
Loss: 226.44432067871094 Accuracy: 0.8974999785423279
Loss: 265.9364929199219 Accuracy: 0.9000000357627869
Loss: 301.4836120605469 Accuracy: 0.9016667008399963
Loss: 332.22296142578125 Accuracy

Loss: 356.82769775390625 Accuracy: 0.9200000166893005
Loss: 440.810302734375 Accuracy: 0.9157142639160156
Total Loss: 460.2520751953125 Total Accuracy: 0.9173228144645691
..........Saving the model..........
========= Epoch 51 Training =========
tensor([[-6.5978,  6.8384]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19866.037442684174
Train steps: 156000, Loss: 1.4305104514278355e-06
tensor([[ 6.1105, -5.8999]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19920.133496046066
Train steps: 156500, Loss: 6.079655122448457e-06
tensor([[ 6.0377, -5.7704]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19973.09640145302
Train steps: 157000, Loss: 7.390948667307384e-06
tensor([[-6.0916,  6.5715]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20026.843572854996
Train steps: 157500, Loss: 3.2186455882765586e-06
tensor([[-6.2927,  6.7650]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20080.513353824615
Train steps: 158000, Loss: 2.1457649381773

tensor([[-7.9554,  8.0988]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22053.80222773552
Train steps: 173500, Loss: 1.1920928244535389e-07
tensor([[-8.0988,  8.0793]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22109.073255062103
Train steps: 174000, Loss: 1.1920928244535389e-07
========= Epoch 56 Testing =========
Loss: 18.00235939025879 Accuracy: 0.9699999690055847
Loss: 133.3569793701172 Accuracy: 0.9350000023841858
Loss: 180.12841796875 Accuracy: 0.9333333373069763
Loss: 269.796630859375 Accuracy: 0.9274999499320984
Loss: 357.9822692871094 Accuracy: 0.9240000247955322
Loss: 480.2693176269531 Accuracy: 0.9183333516120911
Loss: 523.8162841796875 Accuracy: 0.9228571057319641
Total Loss: 585.1328735351562 Total Accuracy: 0.9199475049972534
..........Saving the model..........
========= Epoch 57 Training =========
tensor([[-7.9732,  7.9430]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22220.13875889778
Train steps: 174500, Loss: 1.1920928244535389e-0

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.2639,  0.2181]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 53.781718015670776
Train steps: 500, Loss: 0.48089802265167236
tensor([[-0.3719,  0.4674]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 108.62233567237854
Train steps: 1000, Loss: 1.198410987854004
tensor([[ 0.0495, -0.0918]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 162.82588863372803
Train steps: 1500, Loss: 0.6249675750732422
tensor([[-0.3283,  0.1570]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 217.24743175506592
Train steps: 2000, Loss: 0.9650082588195801
tensor([[-1.1078,  1.3613]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 269.31717324256897
Train steps: 2500, Loss: 0.08126739412546158
tensor([[ 0.1131, -0.2329]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 323.2688443660736
Train steps: 3000, Loss: 0.8810775279998779
========= Epoch 0 Testing =========
Loss: 39.4576416015625 Accuracy: 0.87999999523

Loss: 117.1333236694336 Accuracy: 0.8199999928474426
Loss: 148.67184448242188 Accuracy: 0.8399999737739563
Loss: 183.94186401367188 Accuracy: 0.8440000414848328
Loss: 222.56195068359375 Accuracy: 0.8383333683013916
Loss: 258.1659240722656 Accuracy: 0.8428571224212646
Total Loss: 277.6672058105469 Total Accuracy: 0.8451443314552307
..........Saving the model..........
========= Epoch 6 Training =========
tensor([[-1.5052,  1.8285]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2354.7872495651245
Train steps: 18500, Loss: 0.03504146263003349
tensor([[ 0.4406, -0.6658]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2410.2359302043915
Train steps: 19000, Loss: 0.28575754165649414
tensor([[-1.5022,  1.8103]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2465.140464067459
Train steps: 19500, Loss: 0.03577636554837227
tensor([[-1.4837,  1.7811]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2519.4311928749084
Train steps: 20000, Loss: 0.0374942049384117

tensor([[ 0.5697, -0.8164]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4553.08402633667
Train steps: 36000, Loss: 1.609258770942688
tensor([[-1.6012,  1.9370]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4606.840101957321
Train steps: 36500, Loss: 0.028651215136051178
========= Epoch 11 Testing =========
Loss: 44.46342468261719 Accuracy: 0.7999999523162842
Loss: 77.69279479980469 Accuracy: 0.824999988079071
Loss: 116.47024536132812 Accuracy: 0.8233333826065063
Loss: 153.18984985351562 Accuracy: 0.8199999928474426
Loss: 188.1448516845703 Accuracy: 0.8240000605583191
Loss: 220.6426239013672 Accuracy: 0.8283333778381348
Loss: 263.06500244140625 Accuracy: 0.8285714387893677
Total Loss: 284.9153747558594 Total Accuracy: 0.8280839920043945
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[ 0.6895, -0.9483]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4718.178458452225
Train steps: 37000, Loss: 0.17764373123645782
tensor([

tensor([[-1.6140,  1.8689]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6778.436779022217
Train steps: 53000, Loss: 0.030256425961852074
tensor([[ 0.8500, -1.1812]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6835.619620084763
Train steps: 53500, Loss: 0.12325958907604218
tensor([[-1.7442,  2.0751]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6892.441143512726
Train steps: 54000, Loss: 0.02170592173933983
tensor([[-1.8252,  2.1422]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6949.147933006287
Train steps: 54500, Loss: 0.01874435879290104
========= Epoch 17 Testing =========
Loss: 32.29386901855469 Accuracy: 0.8499999642372131
Loss: 72.97151947021484 Accuracy: 0.8399999737739563
Loss: 97.43477630615234 Accuracy: 0.8600000143051147
Loss: 139.79244995117188 Accuracy: 0.8524999618530273
Loss: 187.1425323486328 Accuracy: 0.8400000333786011
Loss: 228.58148193359375 Accuracy: 0.8350000381469727
Loss: 262.79449462890625 Accuracy: 0.8414285778999

Loss: 217.8247833251953 Accuracy: 0.8633333444595337
Loss: 265.7216491699219 Accuracy: 0.8585714101791382
Total Loss: 284.5232238769531 Total Accuracy: 0.8595800399780273
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-0.0127, -0.0800]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9107.381171703339
Train steps: 70500, Loss: 0.7273605465888977
tensor([[-1.8468,  2.1133]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9164.566426753998
Train steps: 71000, Loss: 0.01888275519013405
tensor([[ 0.3281, -0.4283]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9221.548703193665
Train steps: 71500, Loss: 0.3848313093185425
tensor([[-1.8508,  2.1010]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9278.178364276886
Train steps: 72000, Loss: 0.019038792699575424
tensor([[ 0.0831, -0.1835]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9335.154252290726
Train steps: 72500, Loss: 0.8352689146995544
tensor([[-2.2748

tensor([[-2.4664,  2.8024]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11436.888267278671
Train steps: 88500, Loss: 0.005136626306921244
========= Epoch 28 Testing =========
Loss: 48.152862548828125 Accuracy: 0.85999995470047
Loss: 87.31499481201172 Accuracy: 0.8549999594688416
Loss: 146.26902770996094 Accuracy: 0.8300000429153442
Loss: 171.97442626953125 Accuracy: 0.8499999642372131
Loss: 216.48098754882812 Accuracy: 0.8500000238418579
Loss: 256.9923095703125 Accuracy: 0.846666693687439
Loss: 296.3281555175781 Accuracy: 0.8442857265472412
Total Loss: 312.1560974121094 Total Accuracy: 0.8490813374519348
..........Saving the model..........
========= Epoch 29 Training =========
tensor([[ 1.0837, -1.3404]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11546.764428853989
Train steps: 89000, Loss: 0.08484738320112228
tensor([[-2.5046,  2.8537]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11603.774866580963
Train steps: 89500, Loss: 0.004698071163147688
te

tensor([[ 1.4019, -1.7841]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13639.536846637726
Train steps: 105000, Loss: 3.2265079021453857
tensor([[ 1.1432, -1.4501]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13696.797819137573
Train steps: 105500, Loss: 0.07211031764745712
tensor([[ 1.2652, -1.6650]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13754.078028202057
Train steps: 106000, Loss: 0.05200835317373276
tensor([[-1.7432,  1.8107]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13811.202597856522
Train steps: 106500, Loss: 0.028209179639816284
========= Epoch 34 Testing =========
Loss: 61.59845733642578 Accuracy: 0.8100000023841858
Loss: 115.45789337158203 Accuracy: 0.824999988079071
Loss: 169.8972625732422 Accuracy: 0.8166666626930237
Loss: 214.32540893554688 Accuracy: 0.8274999856948853
Loss: 241.43995666503906 Accuracy: 0.8460000157356262
Loss: 281.6723327636719 Accuracy: 0.8516666889190674
Loss: 307.61865234375 Accuracy: 0.861428558

Loss: 191.97091674804688 Accuracy: 0.8675000071525574
Loss: 223.4395294189453 Accuracy: 0.8720000386238098
Loss: 272.3353271484375 Accuracy: 0.8700000047683716
Loss: 303.8149719238281 Accuracy: 0.8757143020629883
Total Loss: 349.7326354980469 Total Accuracy: 0.8687664270401001
..........Saving the model..........
========= Epoch 40 Training =========
tensor([[ 1.4345, -1.8000]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15966.383578062057
Train steps: 122500, Loss: 3.2730510234832764
tensor([[-2.9444,  3.3316]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16023.63895702362
Train steps: 123000, Loss: 0.001879117451608181
tensor([[-2.9565,  3.3709]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16080.716725111008
Train steps: 123500, Loss: 0.0017849955474957824
tensor([[-2.8957,  3.2756]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16137.325509548187
Train steps: 124000, Loss: 0.002086249878630042
tensor([[ 1.5256, -1.9040]], device='cuda:0',

tensor([[-3.0639,  3.4316]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18183.974753141403
Train steps: 139500, Loss: 0.0015090041561052203
tensor([[ 1.7500, -2.1746]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18241.109151124954
Train steps: 140000, Loss: 0.01955738104879856
tensor([[-3.1871,  3.5945]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18298.05347442627
Train steps: 140500, Loss: 0.0011337526375427842
========= Epoch 45 Testing =========
Loss: 26.63603973388672 Accuracy: 0.9199999570846558
Loss: 71.70606994628906 Accuracy: 0.9099999666213989
Loss: 108.4427261352539 Accuracy: 0.9000000357627869
Loss: 171.78839111328125 Accuracy: 0.887499988079071
Loss: 234.60755920410156 Accuracy: 0.878000020980835
Loss: 314.7750549316406 Accuracy: 0.8666666746139526
Loss: 368.4123229980469 Accuracy: 0.8657142519950867
Total Loss: 397.6128845214844 Total Accuracy: 0.8661417365074158
..........Saving the model..........
========= Epoch 46 Training =========

tensor([[-2.8820,  2.9419]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20393.903259277344
Train steps: 156000, Loss: 0.0029517910443246365
tensor([[-3.3263,  3.7296]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20451.038145780563
Train steps: 156500, Loss: 0.0008619884611107409
tensor([[-3.4278,  3.8643]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20508.023778438568
Train steps: 157000, Loss: 0.0006806917954236269
tensor([[-3.4127,  3.8591]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20565.08193588257
Train steps: 157500, Loss: 0.0006946296198293567
tensor([[-3.4391,  3.9377]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20622.071721076965
Train steps: 158000, Loss: 0.0006254147156141698
tensor([[-3.3705,  3.7907]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20678.934413194656
Train steps: 158500, Loss: 0.0007757514249533415
========= Epoch 51 Testing =========
Loss: 85.37056732177734 Accuracy: 0.8199999928474426

========= Epoch 56 Testing =========
Loss: 66.18183135986328 Accuracy: 0.8700000047683716
Loss: 149.54348754882812 Accuracy: 0.8499999642372131
Loss: 209.785888671875 Accuracy: 0.8666666746139526
Loss: 294.73895263671875 Accuracy: 0.85999995470047
Loss: 330.0809326171875 Accuracy: 0.8720000386238098
Loss: 423.4616394042969 Accuracy: 0.8683333396911621
Loss: 502.42889404296875 Accuracy: 0.8642857074737549
Total Loss: 529.8434448242188 Total Accuracy: 0.8700787425041199
..........Saving the model..........
========= Epoch 57 Training =========
tensor([[-3.7128,  4.2045]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22840.84547638893
Train steps: 174500, Loss: 0.00036435641231946647
tensor([[-3.7031,  4.2165]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22898.00889134407
Train steps: 175000, Loss: 0.0003635222092270851
tensor([[ 2.2020, -2.6864]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22954.932529211044
Train steps: 175500, Loss: 0.00750496005639433

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.1955,  0.2069]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 53.45388221740723
Train steps: 500, Loss: 0.5120705962181091
tensor([[-0.3490,  0.3490]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 110.59729170799255
Train steps: 1000, Loss: 0.403863787651062
tensor([[-0.0734,  0.0924]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 167.7573218345642
Train steps: 1500, Loss: 0.7794998288154602
tensor([[-0.0966,  0.1667]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 224.97334933280945
Train steps: 2000, Loss: 0.833448052406311
tensor([[ 0.3105, -0.2474]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 282.03758573532104
Train steps: 2500, Loss: 1.0104694366455078
tensor([[ 0.5124, -0.3922]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 339.2468385696411
Train steps: 3000, Loss: 1.2443938255310059
========= Epoch 0 Testing =========
Loss: 25.13821029663086 Accuracy: 0.899999976158142

Loss: 86.26812744140625 Accuracy: 0.8766666650772095
Loss: 106.82814025878906 Accuracy: 0.8824999928474426
Loss: 129.32313537597656 Accuracy: 0.8880000710487366
Loss: 154.10357666015625 Accuracy: 0.8883333802223206
Loss: 179.5657501220703 Accuracy: 0.8899999856948853
Total Loss: 191.5792236328125 Total Accuracy: 0.8923884630203247
..........Saving the model..........
========= Epoch 6 Training =========
tensor([[-2.2638,  2.4721]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2444.946663379669
Train steps: 18500, Loss: 0.008735774084925652
tensor([[-2.4609,  2.6742]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2502.0284848213196
Train steps: 19000, Loss: 0.0058691781014204025
tensor([[-1.6656,  1.8094]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2559.1792900562286
Train steps: 19500, Loss: 0.03049337863922119
tensor([[-2.2678,  2.4603]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2616.1000497341156
Train steps: 20000, Loss: 0.0088041936978

tensor([[-2.7899,  2.9942]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4661.248102426529
Train steps: 35500, Loss: 0.003071236191317439
tensor([[-2.6322,  2.8354]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4718.45231461525
Train steps: 36000, Loss: 0.004212197847664356
tensor([[-1.8541,  2.0377]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4775.6188015937805
Train steps: 36500, Loss: 0.02020316570997238
========= Epoch 11 Testing =========
Loss: 28.00447654724121 Accuracy: 0.8799999952316284
Loss: 47.650779724121094 Accuracy: 0.9049999713897705
Loss: 80.0798568725586 Accuracy: 0.9033333659172058
Loss: 102.49625396728516 Accuracy: 0.9099999666213989
Loss: 140.09039306640625 Accuracy: 0.8960000276565552
Loss: 167.12631225585938 Accuracy: 0.8950000405311584
Loss: 203.75099182128906 Accuracy: 0.8899999856948853
Total Loss: 209.49945068359375 Total Accuracy: 0.8976377844810486
..........Saving the model..........
========= Epoch 12 Training =========
t

tensor([[-1.7756,  2.0022]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6880.594488620758
Train steps: 52000, Loss: 0.02261561155319214
tensor([[-2.6015,  2.7904]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6937.464066028595
Train steps: 52500, Loss: 0.004542864393442869
tensor([[-2.8908,  3.0928]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6994.563921689987
Train steps: 53000, Loss: 0.002516557462513447
tensor([[-2.7745,  2.9726]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7051.86657333374
Train steps: 53500, Loss: 0.0031869830563664436
tensor([[-3.0533,  3.2932]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7108.853044748306
Train steps: 54000, Loss: 0.0017513189231976867
tensor([[ 2.4069, -2.2408]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7165.888613700867
Train steps: 54500, Loss: 0.009537843056023121
========= Epoch 17 Testing =========
Loss: 36.665706634521484 Accuracy: 0.8799999952316284
Loss: 69.944343

========= Epoch 22 Testing =========
Loss: 36.1944465637207 Accuracy: 0.9099999666213989
Loss: 56.79429244995117 Accuracy: 0.9199999570846558
Loss: 78.67720031738281 Accuracy: 0.9200000166893005
Loss: 107.95523071289062 Accuracy: 0.9199999570846558
Loss: 142.37571716308594 Accuracy: 0.9120000600814819
Loss: 169.1671600341797 Accuracy: 0.9133333563804626
Loss: 194.9954833984375 Accuracy: 0.9114285707473755
Total Loss: 213.04090881347656 Total Accuracy: 0.9094488024711609
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-3.2872,  3.5049]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9321.691788196564
Train steps: 70500, Loss: 0.0011219641892239451
tensor([[-1.5510,  1.7228]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9378.724530220032
Train steps: 71000, Loss: 0.03716541454195976
tensor([[-2.3685,  2.6158]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9436.061737537384
Train steps: 71500, Loss: 0.0068207294680178165
te

tensor([[-3.3287,  3.5631]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11482.207255601883
Train steps: 87000, Loss: 0.0010155049385502934
tensor([[ 3.7796, -3.7146]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11539.50728726387
Train steps: 87500, Loss: 0.0005561950383707881
tensor([[-2.7303,  2.9781]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11596.763882875443
Train steps: 88000, Loss: 0.0033124596811830997
tensor([[-3.4707,  3.7020]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11653.64885687828
Train steps: 88500, Loss: 0.0007669368060305715
========= Epoch 28 Testing =========
Loss: 11.935148239135742 Accuracy: 0.9699999690055847
Loss: 36.147987365722656 Accuracy: 0.9449999928474426
Loss: 65.23657989501953 Accuracy: 0.9366666674613953
Loss: 110.3912582397461 Accuracy: 0.9300000071525574
Loss: 132.7864532470703 Accuracy: 0.9340000152587891
Loss: 139.6254425048828 Accuracy: 0.9399999976158142
Loss: 187.607177734375 Accuracy: 0.932857

Loss: 314.9307861328125 Accuracy: 0.9128571152687073
Total Loss: 352.33978271484375 Total Accuracy: 0.9094488024711609
..........Saving the model..........
========= Epoch 34 Training =========
tensor([[-3.6536,  3.8800]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13756.990903615952
Train steps: 104000, Loss: 0.0005346299149096012
tensor([[-3.6847,  3.9061]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13814.238873720169
Train steps: 104500, Loss: 0.0005049622268415987
tensor([[ 4.1565, -4.1871]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13871.507152318954
Train steps: 105000, Loss: 0.0002379134384682402
tensor([[-3.4225,  3.6502]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13928.831000089645
Train steps: 105500, Loss: 0.0008475763606838882
tensor([[-3.5459,  3.7601]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13985.970612049103
Train steps: 106000, Loss: 0.0006712805479764938
tensor([[-3.5537,  3.8205]], device='cuda:0', 

tensor([[-4.3444,  4.5687]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16032.190695762634
Train steps: 121500, Loss: 0.00013457823661156
tensor([[-4.0596,  4.2963]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16089.053870677948
Train steps: 122000, Loss: 0.0002349338901694864
========= Epoch 39 Testing =========
Loss: 56.74208068847656 Accuracy: 0.9199999570846558
Loss: 86.04671478271484 Accuracy: 0.9399999976158142
Loss: 132.28309631347656 Accuracy: 0.9333333373069763
Loss: 186.6885223388672 Accuracy: 0.9274999499320984
Loss: 250.00164794921875 Accuracy: 0.9220000505447388
Loss: 301.9814758300781 Accuracy: 0.92166668176651
Loss: 360.8750305175781 Accuracy: 0.918571412563324
Total Loss: 419.8887939453125 Total Accuracy: 0.913385808467865
..........Saving the model..........
========= Epoch 40 Training =========
tensor([[-4.4181,  4.6107]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 16201.460089683533
Train steps: 122500, Loss: 0.00011991736391792074

tensor([[ 7.3490, -7.4809]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18225.784349679947
Train steps: 138000, Loss: 3.576278118089249e-07
tensor([[-6.3675,  7.1470]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18285.121951818466
Train steps: 138500, Loss: 1.311301275563892e-06
tensor([[-6.3609,  7.0164]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18344.546268463135
Train steps: 139000, Loss: 1.5497193999181036e-06
tensor([[-6.5763,  7.3134]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18403.861485481262
Train steps: 139500, Loss: 9.536738616588991e-07
tensor([[ 6.0686, -5.9260]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18463.085924625397
Train steps: 140000, Loss: 6.198863957251888e-06
tensor([[-6.6543,  7.4385]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 18522.21715259552
Train steps: 140500, Loss: 7.152555667744309e-07
========= Epoch 45 Testing =========
Loss: 145.98948669433594 Accuracy: 0.87999999523162

Loss: 1084.58349609375 Accuracy: 0.878333330154419
Loss: 1290.0145263671875 Accuracy: 0.8757143020629883
Total Loss: 1410.357421875 Total Accuracy: 0.8753280639648438
..........Saving the model..........
========= Epoch 51 Training =========
tensor([[-8.3847,  8.8956]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20191.536287546158
Train steps: 156000, Loss: 0.0
tensor([[-8.6918,  9.1734]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20233.488503932953
Train steps: 156500, Loss: 0.0
tensor([[10.0412, -9.9601]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20275.23727941513
Train steps: 157000, Loss: 0.0
tensor([[ 9.1506, -9.0365]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20317.011969566345
Train steps: 157500, Loss: 0.0
tensor([[ 9.6562, -9.5175]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20358.900415420532
Train steps: 158000, Loss: 0.0
tensor([[ 9.9827, -9.8184]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20400

Loss: 861.3868408203125 Accuracy: 0.9100000262260437
Loss: 965.7464599609375 Accuracy: 0.9142857193946838
Total Loss: 1023.4805297851562 Total Accuracy: 0.9173228144645691
..........Saving the model..........
========= Epoch 57 Training =========
tensor([[-10.0680,   9.6798]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22192.176475048065
Train steps: 174500, Loss: 0.0
tensor([[-10.1174,   9.6535]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22234.37130355835
Train steps: 175000, Loss: 0.0
tensor([[ 10.7095, -10.1163]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22276.89575099945
Train steps: 175500, Loss: 0.0
tensor([[-10.0075,   9.5620]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22319.121194839478
Train steps: 176000, Loss: 0.0
tensor([[ 10.9801, -10.3726]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22361.341942071915
Train steps: 176500, Loss: 0.0
tensor([[10.2159, -9.6439]], device='cuda:0', grad_fn=<AddmmBackward0>)
Tra

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.2743,  0.3473]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 42.63399910926819
Train steps: 500, Loss: 0.4298951029777527
tensor([[ 0.3047, -0.3034]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 84.98025941848755
Train steps: 1000, Loss: 1.0426806211471558
tensor([[-1.6573,  1.9642]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 127.5066123008728
Train steps: 1500, Loss: 0.02639252133667469
tensor([[-1.1079,  1.3045]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 169.999529838562
Train steps: 2000, Loss: 0.08581434190273285
tensor([[ 0.3032, -0.3498]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 212.30496335029602
Train steps: 2500, Loss: 1.072028636932373
tensor([[ 0.1895, -0.2252]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 254.61848855018616
Train steps: 3000, Loss: 0.5071125030517578
========= Epoch 0 Testing =========
Loss: 44.8321418762207 Accuracy: 0.779999971389770

Loss: 106.57395935058594 Accuracy: 0.846666693687439
Loss: 137.37086486816406 Accuracy: 0.8449999690055847
Loss: 174.41775512695312 Accuracy: 0.8440000414848328
Loss: 200.83824157714844 Accuracy: 0.8533333539962769
Loss: 227.27061462402344 Accuracy: 0.8557142615318298
Total Loss: 245.89300537109375 Total Accuracy: 0.8556430339813232
..........Saving the model..........
========= Epoch 6 Training =========
tensor([[ 0.5602, -0.6171]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1920.7652056217194
Train steps: 18500, Loss: 0.26859182119369507
tensor([[-2.5871,  2.9894]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1962.7877080440521
Train steps: 19000, Loss: 0.00377858174033463
tensor([[ 1.0600, -1.1948]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2004.9939985275269
Train steps: 19500, Loss: 0.0997481420636177
tensor([[-2.1570,  2.4920]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 2048.273790359497
Train steps: 20000, Loss: 0.009526153095066

tensor([[ 0.6347, -0.6463]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4125.4654376506805
Train steps: 36000, Loss: 0.24511387944221497
tensor([[-2.4287,  2.7919]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4174.811768770218
Train steps: 36500, Loss: 0.005389920435845852
========= Epoch 11 Testing =========
Loss: 29.056270599365234 Accuracy: 0.8499999642372131
Loss: 51.168087005615234 Accuracy: 0.875
Loss: 91.20195007324219 Accuracy: 0.8566666841506958
Loss: 123.42314910888672 Accuracy: 0.85999995470047
Loss: 147.2959747314453 Accuracy: 0.8660000562667847
Loss: 172.9010467529297 Accuracy: 0.8700000047683716
Loss: 202.7325897216797 Accuracy: 0.8728571534156799
Total Loss: 220.86349487304688 Total Accuracy: 0.8753280639648438
..........Saving the model..........
========= Epoch 12 Training =========
tensor([[ 1.6254, -1.7845]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4280.168583393097
Train steps: 37000, Loss: 0.03250884264707565
tensor([[-2.4484,

tensor([[-3.2506,  3.7112]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6352.197224378586
Train steps: 53000, Loss: 0.0009470268851146102
tensor([[-3.6661,  4.1746]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6408.724236011505
Train steps: 53500, Loss: 0.0003933132975362241
tensor([[-3.0195,  3.3756]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6465.190373182297
Train steps: 54000, Loss: 0.0016683719586580992
tensor([[-3.7264,  4.2700]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6521.66215467453
Train steps: 54500, Loss: 0.000336590368533507
========= Epoch 17 Testing =========
Loss: 25.340158462524414 Accuracy: 0.8799999952316284
Loss: 58.98490524291992 Accuracy: 0.875
Loss: 79.65312194824219 Accuracy: 0.89000004529953
Loss: 104.44207763671875 Accuracy: 0.8899999856948853
Loss: 145.3985137939453 Accuracy: 0.8840000629425049
Loss: 171.59957885742188 Accuracy: 0.8816666603088379
Loss: 204.1066436767578 Accuracy: 0.8814285397529602
Total 

Loss: 154.2828369140625 Accuracy: 0.8980000615119934
Loss: 176.4954833984375 Accuracy: 0.8983333706855774
Loss: 203.47760009765625 Accuracy: 0.8985714316368103
Total Loss: 218.012939453125 Total Accuracy: 0.8989500999450684
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-3.9925,  4.5166]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8648.313585042953
Train steps: 70500, Loss: 0.0002015625941567123
tensor([[ 2.2864, -2.5235]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8704.909178495407
Train steps: 71000, Loss: 0.008115412667393684
tensor([[-4.3055,  4.8894]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8761.458574771881
Train steps: 71500, Loss: 0.00010156114876735955
tensor([[-3.9714,  4.5395]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8817.774139642715
Train steps: 72000, Loss: 0.0002012050390476361
tensor([[-3.4876,  3.8982]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8874.220877885818

tensor([[ 2.8252, -3.0459]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10892.399100065231
Train steps: 88000, Loss: 0.002815808402374387
tensor([[ 1.2796, -1.3508]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10948.98005437851
Train steps: 88500, Loss: 0.06957534700632095
========= Epoch 28 Testing =========
Loss: 31.08346939086914 Accuracy: 0.9399999976158142
Loss: 62.58393478393555 Accuracy: 0.9350000023841858
Loss: 98.41275787353516 Accuracy: 0.9233333468437195
Loss: 133.10121154785156 Accuracy: 0.9149999618530273
Loss: 167.0741424560547 Accuracy: 0.9120000600814819
Loss: 199.768798828125 Accuracy: 0.9083333611488342
Loss: 257.2051696777344 Accuracy: 0.8985714316368103
Total Loss: 275.0730285644531 Total Accuracy: 0.8989500999450684
..........Saving the model..........
========= Epoch 29 Training =========
tensor([[ 3.0093, -3.2768]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11058.806759119034
Train steps: 89000, Loss: 0.001860198681242764
tens

tensor([[-5.0104,  5.5443]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13080.1265335083
Train steps: 104500, Loss: 2.610649426060263e-05
tensor([[ 3.2068, -3.4893]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13136.881619930267
Train steps: 105000, Loss: 0.0012349606258794665
tensor([[-4.8759,  5.4997]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13193.337440252304
Train steps: 105500, Loss: 3.123234637314454e-05
tensor([[ 3.1440, -3.4596]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13249.844747066498
Train steps: 106000, Loss: 0.0013546108966693282
tensor([[-4.8982,  5.5021]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 13306.34444117546
Train steps: 106500, Loss: 3.039790863113012e-05
========= Epoch 34 Testing =========
Loss: 47.15847396850586 Accuracy: 0.8999999761581421
Loss: 94.16275024414062 Accuracy: 0.8999999761581421
Loss: 135.0166015625 Accuracy: 0.9000000357627869
Loss: 190.75070190429688 Accuracy: 0.8924999833106

========= Epoch 39 Testing =========
Loss: 80.9375 Accuracy: 0.85999995470047
Loss: 133.056640625 Accuracy: 0.8799999952316284
Loss: 174.0369873046875 Accuracy: 0.8966667056083679
Loss: 207.3330078125 Accuracy: 0.9049999713897705
Loss: 251.9178924560547 Accuracy: 0.9020000696182251
Loss: 285.8402099609375 Accuracy: 0.9083333611488342
Loss: 341.1054992675781 Accuracy: 0.9071428179740906
Total Loss: 364.1429748535156 Total Accuracy: 0.9068241715431213
..........Saving the model..........
========= Epoch 40 Training =========
tensor([[ 4.2062, -4.4804]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15435.895269870758
Train steps: 122500, Loss: 0.00016878610767889768
tensor([[ 4.5148, -4.8752]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15492.613379478455
Train steps: 123000, Loss: 8.356221951544285e-05
tensor([[-5.3050,  5.9476]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 15549.383446931839
Train steps: 123500, Loss: 1.299372706853319e-05
tensor([[-4.69

tensor([[-6.2127,  6.8931]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17562.241236925125
Train steps: 139000, Loss: 2.0265558760002023e-06
tensor([[ 5.3842, -5.6808]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17618.596565008163
Train steps: 139500, Loss: 1.5616295058862306e-05
tensor([[ 5.1622, -5.4686]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17675.042618751526
Train steps: 140000, Loss: 2.4199192921514623e-05
tensor([[ 5.0063, -5.2955]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 17731.530070781708
Train steps: 140500, Loss: 3.361645576660521e-05
========= Epoch 45 Testing =========
Loss: 85.78851318359375 Accuracy: 0.8899999856948853
Loss: 149.16981506347656 Accuracy: 0.8849999904632568
Loss: 231.66567993164062 Accuracy: 0.8700000047683716
Loss: 262.6794128417969 Accuracy: 0.8824999928474426
Loss: 342.914306640625 Accuracy: 0.878000020980835
Loss: 380.0069580078125 Accuracy: 0.8833333253860474
Loss: 418.8844909667969 Accuracy: 

Loss: 382.5086975097656 Accuracy: 0.9066666960716248
Loss: 462.8916931152344 Accuracy: 0.9057142734527588
Total Loss: 491.20928955078125 Total Accuracy: 0.9094488024711609
..........Saving the model..........
========= Epoch 51 Training =========
tensor([[ 6.1437, -6.5391]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19803.051523447037
Train steps: 156000, Loss: 3.099436753473128e-06
tensor([[ 6.5735, -6.8363]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19859.5703458786
Train steps: 156500, Loss: 1.5497195136049413e-06
tensor([[ 7.0114, -7.2705]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19916.02338027954
Train steps: 157000, Loss: 5.960462772236497e-07
tensor([[-6.5673,  7.2275]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 19972.710739850998
Train steps: 157500, Loss: 1.0728830375228426e-06
tensor([[ 6.2929, -6.5572]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 20029.103978157043
Train steps: 158000, Loss: 2.62260073213838

tensor([[-8.0692,  8.7539]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22048.231092453003
Train steps: 173500, Loss: 0.0
tensor([[ 8.4958, -8.7522]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22104.907641649246
Train steps: 174000, Loss: 0.0
========= Epoch 56 Testing =========
Loss: 75.70745086669922 Accuracy: 0.9300000071525574
Loss: 147.08444213867188 Accuracy: 0.9199999570846558
Loss: 231.51153564453125 Accuracy: 0.9166666865348816
Loss: 375.5428771972656 Accuracy: 0.9049999713897705
Loss: 479.241943359375 Accuracy: 0.9080000519752502
Loss: 626.6896362304688 Accuracy: 0.9033333659172058
Loss: 713.5855102539062 Accuracy: 0.9085714221000671
Total Loss: 748.6110229492188 Total Accuracy: 0.9094488024711609
..........Saving the model..........
========= Epoch 57 Training =========
tensor([[ 8.5877, -8.8660]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 22215.015155792236
Train steps: 174500, Loss: 0.0
tensor([[-8.3170,  9.0529]], device='cuda:0', gra