In [1]:
import torch
import torchvision
# from torch.utils.tensorboard import SummaryWriter
import time
from torch import nn
from torch.utils.data import DataLoader
from load_data import MyData  # self-made
from torchvision import transforms
from tqdm import tqdm_notebook as tqdm # View procedure
import os
import scipy.io
from random import random
import numpy as np
import gc
from torch.utils.tensorboard import SummaryWriter
from net_cnn_lstm6 import MyNetwork
from torchnlp.word_to_vector import GloVe
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [2]:
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ random
BATCH_SIZE = 1
C,H,W = 1,1,2400
# learn_rate = 0.0005
learn_rate=0.001
# num_epochs=50
num_epochs = 60

# ================================================ optimizer
import torch.optim as optim
device = torch.device("cuda:0")
gc.collect()
torch.cuda.empty_cache()
# ==损失函数权重
# ======== 二分类HC/DOC
# 计算总样本数量
# condition1
# total_samples = 887 + 985 + 879
# condition2
# total_samples = 929 + 1029 + 886
# condition3
# total_samples = 887 + 975 + 879
# rest
total_samples = 852 + 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 887, total_samples / (985 + 879)]
# condition2
# weights = [total_samples / 929, total_samples / (1029 + 886)]
# condition3
weights = [total_samples / 852, total_samples / (1051 + 872)]

# ======== 二分类MCS/UWS
# 计算总样本数量
# condition1
# total_samples = 985 + 879
# condition2
# total_samples = 1029 + 886
# condition3
# total_samples = 975 + 879
# rest
# total_samples = 1051 + 872
# 计算每个类别的权重
# condition1
# weights = [total_samples / 985, total_samples / 879]
# condition2
# weights = [total_samples / 1029, total_samples / 886]
# condition3
# weights = [total_samples / 975, total_samples / 879]
# condition3
# weights = [total_samples / 1051, total_samples / 872]
# 将权重转换为张量
weights_tensor = torch.tensor(weights, device=device)

# 定义交叉熵损失函数并设置权重
criterion = nn.CrossEntropyLoss(weight=weights_tensor)
# criterion = nn.CrossEntropyLoss()
criterion = criterion.to(device)

In [3]:
def make_dataset(dataset,mode):
    # find the fold file
    count = 0
    for person in range(len(dataset)):
        filename = os.path.join(dataset.path, dataset.file_path[person])
        # extract the pure name of the file
        parts = filename.split("\\")
        file_name = parts[-1]
        name_without_extension = file_name.split(".")[0]
        # label or data
        file_last = name_without_extension.split("_")[-1]
        if file_last.isdigit(): # data
            # is this fold or not
            if int(file_last) == fold: # yes
                print(filename)
                count = count + 1
                data_map = torch.load(filename)
                # train or test
                if name_without_extension.split("_")[-2] == "train":
                    for i in range(data_map.size(0)):
                        train_data.append(data_map[i])
                elif name_without_extension.split("_")[-2] == "test":
                    for i in range(data_map.size(0)):
                        test_data.append(data_map[i])
                if count == 4:
                    del data_map
                    gc.collect()
                    torch.cuda.empty_cache() 
                    break
            else:   # not
                pass
        else: # label
            file_last = name_without_extension.split("_")[-4]
            file_mode = name_without_extension.split("_")[-2]
            if file_mode == mode.split("_")[-1]: # is this mode or not
                # is this fold or not
                if int(file_last) == fold: # yes
                    print(filename)
                    count = count + 1
                    data_map = torch.load(filename)
                    # train or test
                    if name_without_extension.split("_")[-5] == "train":
                        for i in range(data_map.size(0)):
                            train_label.append(data_map[i])
                    elif name_without_extension.split("_")[-5] == "test":
                        for i in range(data_map.size(0)):
                            test_label.append(data_map[i])
                    if count == 4:
                        del data_map
                        gc.collect()
                        torch.cuda.empty_cache() 
                        break
                else:   # not
                    pass
            else:
                pass
        del filename, parts, file_name, name_without_extension, file_last
        gc.collect()
        torch.cuda.empty_cache()    
# 定义LSTM超参数
input_size = 64  # 输入特征维度
# hidden_size = 64  # 隐藏单元数量
# input_size = 59  # 输入特征维度
hidden_size = 64  # 隐藏单元数量
num_layers = 2  # LSTM层数
output_size = 2  # 输出类别数量
# 创建模型实例
# model_list = ['', '_CNN', '_CNN_spa', '_CNN_spa_lstm']
# model_name = model_list[0]
# if model_name == model_list[0]: #  CascadeCept
#     from network_cnn_lstm import MyNetwork
# elif model_name == model_list[1]: #  CNN
#     from network_cnn_lstm_2 import MyNetwork
# elif model_name == model_list[2]: # CascadeCept_1
#     from network_cnn_lstm_3 import MyNetwork
# elif model_name == model_list[3]: # CascadeCept_2
#     from network_cnn_lstm_4 import MyNetwork
model_list = ['_1', '_2', '_3', '_4','_5','_6','_7','_8','_9','_10','_11']
model_name = model_list[0]
if model_name == model_list[0]: 
    from net_cnn_lstm1 import MyNetwork
elif model_name == model_list[1]: 
    from net_cnn_lstm2 import MyNetwork
elif model_name == model_list[2]: 
    from net_cnn_lstm3 import MyNetwork
elif model_name == model_list[3]: 
    from net_cnn_lstm4 import MyNetwork
elif model_name == model_list[4]: 
    from net_cnn_lstm5 import MyNetwork
elif model_name == model_list[5]: 
    from net_cnn_lstm6 import MyNetwork
elif model_name == model_list[6]: 
    from net_cnn_lstm7 import MyNetwork
elif model_name == model_list[7]: 
    from net_cnn_lstm8 import MyNetwork
elif model_name == model_list[8]: 
    from net_cnn_lstm9 import MyNetwork
elif model_name == model_list[9]: 
    from net_cnn_lstm10 import MyNetwork
elif model_name == model_list[10]: 
    from net_cnn_lstm11 import MyNetwork
model = MyNetwork(input_size, hidden_size, num_layers, output_size)
model = model.to(device)

# experimental dir: rest, conditionA, conditionB, conditionC
exper_dir = "rest"
# ————————————————————————————————————————check this for every run!!!!!!!!!!!!!!!!
trial="_1"
# root_dir = f"../data/eegmap_split/{exper_dir}"
root_dir = f"../data/eegmap_split_new/{exper_dir}"
# classification = "hc_doc"/doc or "mcs_uws"/uws
classification = "hc_doc"
# classification = "mcs_uws"
fold_num = 5
best_val_loss = float('inf')
for fold in tqdm(range(5)):
    # train num folds
#     fold = 0 # 选择折数
    # -- prepare datasets
    train_data = []
    train_label = []
    test_data = []
    test_label = []
    
    if classification == "hc_doc":
        # ---- hc
        dataset = MyData(root_dir, "train", "hc") # hc
        make_dataset(dataset,classification)
        dataset = MyData(root_dir, "test", "hc") # hc
        make_dataset(dataset,classification)
    # ---- mcs
    dataset = MyData(root_dir, "train", "mcs") # mcs
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "mcs") # hc
    make_dataset(dataset,classification)
    # ---- uws
    dataset = MyData(root_dir, "train", "uws") # uws
    make_dataset(dataset,classification)
    dataset = MyData(root_dir, "test", "uws") # hc
    make_dataset(dataset,classification)
    
    print(torch.stack(train_data).size())
    print(torch.stack(train_label).size())
    print(torch.stack(test_data).size())
    print(torch.stack(test_label).size())
    del dataset
    gc.collect()
    torch.cuda.empty_cache()  
    
    train_data = torch.stack(train_data)
    train_label = torch.stack(train_label)
    test_data = torch.stack(test_data)
    test_label = torch.stack(test_label)
    # train dataset
    train_td = TensorDataset(train_data, train_label)
    train_loader = DataLoader(train_td, batch_size = BATCH_SIZE, shuffle = True)
    # test dataset
    test_td = TensorDataset(test_data, test_label)
    test_loader = DataLoader(test_td, batch_size = BATCH_SIZE, shuffle = True)
    del train_data, train_label, test_data, test_label, train_td, test_td
    gc.collect()
    torch.cuda.empty_cache()
    
    # set model for each fold
    model = MyNetwork(input_size, hidden_size, num_layers, output_size)
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr = learn_rate)
    scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10, 30, 50], gamma=0.2)
#     scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5, verbose=True)
    # -- start training
    start_time = time.time()
    # train and test step records
    total_train_step = 0
    total_test_step = 0
    min_test_loss = 1000
    # add Tensorboard
#     writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_train_{fold}")
#     writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_{fold}")
#     writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}/logs_test_acc_{fold}")
    writer_train = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_train_{fold}")
    writer_valid = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_{fold}")
    writer_valid_acc = SummaryWriter(f"../logs/{classification}/{exper_dir}{model_name}{trial}/logs_test_acc_{fold}")
    for i in tqdm(range(num_epochs)):  
        print(f"========= Epoch {i} Training =========")
        # train steps
        model.train()
        for data in train_loader:
            # x, y
            data_map, label=data
            data_map_reshaped = torch.reshape(data_map, (99, 1, 1, 2400))
#             data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
            label_int = label.long()
            data_map_reshaped=data_map_reshaped.to(device)
            label_int=label_int.to(device)
            del data_map, label
            gc.collect()
            torch.cuda.empty_cache()
            # y_pred
            label_pred = model(data_map_reshaped)
            # Loss Computation and Optimization
            loss = criterion(label_pred,label_int)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            # draw tensorboard
            total_train_step = total_train_step + 1
            # print info
            if total_train_step % 500 == 0:
                end_time = time.time()
                print(label_pred)
                print(f"Train time: {end_time - start_time}")
                print(f"Train steps: {total_train_step}, Loss: {loss.item()}")
            writer_train.add_scalar("train_loss",loss.item(),total_train_step)
            # Clear gpu
            del data, data_map_reshaped, label_int, label_pred, loss
            gc.collect()
            torch.cuda.empty_cache()
        
        # Evaluation and save the best model
        print(f"========= Epoch {i} Testing =========")
        model.eval()
        test_loss = 0
        total_test_loss = 0
        test_count = 0
        total_test_acc = 0
        with torch.no_grad():
            for data in test_loader:
                test_count = test_count + 1
                # x, y
                data_map, label=data
                data_map_reshaped = torch.reshape(data_map, (99, 1, 1, 2400))
#                 data_map_reshaped = torch.reshape(data_map, (59, 1, 1, 2400))
                label_int = label.long()
                data_map_reshaped = data_map_reshaped.to(device)
                label_int = label_int.to(device)
                del data_map, label
                gc.collect()
                torch.cuda.empty_cache()
                # y_pred
                label_pred_test = model(data_map_reshaped)
                loss = criterion(label_pred_test,label_int)
#                 print(label_pred_test)
                # accuracy 
                total_test_acc = total_test_acc + ((label_pred_test.argmax(1)) == label_int).sum()
                # change lr
                test_loss += loss.item()
                test_loss /= len(test_loader)
                if test_loss < best_val_loss:
                    best_val_loss = test_loss
                scheduler.step()
                # draw tensorboad
                total_test_loss = total_test_loss + loss
                if test_count % 100 == 0:
                    print(f"Loss: {total_test_loss} Accuracy: {total_test_acc/test_count}")
                # Clear gpu
                del data_map_reshaped, label_int, label_pred_test, loss, data
                gc.collect()
                torch.cuda.empty_cache()
        print(f"Total Loss: {total_test_loss} Total Accuracy: {total_test_acc/test_count}")
        writer_valid.add_scalar("test_loss", total_test_loss, total_test_step)
        writer_valid_acc.add_scalar("test_acc", total_test_acc/test_count, total_test_step)
        total_test_step = total_test_step + 1
        print("..........Saving the model..........")
#         torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}/Fold{fold}_Epoch{i}.pt") 
        torch.save(model.state_dict(),f"../models/{classification}/{exper_dir}{model_name}{trial}/Fold{fold}_Epoch{i}.pt") 
#         if total_test_loss < min_test_loss:
#             min_test_loss = total_test_loss
#             print("..........Saving the model..........")
#             torch.save(model.state_dict(),f"../model/{exper_dir}/Fold{fold}_Epoch{i}.pt")

D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:116: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/5 [00:00<?, ?it/s]

../data/eegmap_split_new/rest\train\hc\rest_hc_train_0.pt
../data/eegmap_split_new/rest\train\hc\rest_hc_train_0_hc_doc_label.pt
../data/eegmap_split_new/rest\test\hc\rest_hc_test_0.pt
../data/eegmap_split_new/rest\test\hc\rest_hc_test_0_hc_doc_label.pt
../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_0.pt
../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_0_hc_doc_label.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_0.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_0_hc_doc_label.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_0.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_0_hc_doc_label.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_0.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_0_hc_doc_label.pt
torch.Size([2221, 2400, 9, 11])
torch.Size([2221])
torch.Size([554, 2400, 9, 11])
torch.Size([554])


D:\Anaconda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:183: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.2977,  0.3033]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 39.553218126297
Train steps: 500, Loss: 1.0381176471710205
tensor([[-0.1362,  0.1727]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 76.90772080421448
Train steps: 1000, Loss: 0.5505867600440979
tensor([[-1.4924,  1.2745]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 117.23744201660156
Train steps: 1500, Loss: 0.060956891626119614
tensor([[ 0.9425, -0.5957]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 154.67018842697144
Train steps: 2000, Loss: 0.1945616751909256
========= Epoch 0 Testing =========
Loss: 33.275997161865234 Accuracy: 0.8399999737739563
Loss: 65.82941436767578 Accuracy: 0.8499999642372131
Loss: 96.02579498291016 Accuracy: 0.8633333444595337
Loss: 125.57936096191406 Accuracy: 0.8650000095367432
Loss: 149.37269592285156 Accuracy: 0.8800000548362732
Total Loss: 168.28793334960938 Total Accuracy: 0.8772563338279724
........

========= Epoch 7 Testing =========
Loss: 24.258655548095703 Accuracy: 0.9199999570846558
Loss: 48.923828125 Accuracy: 0.9049999713897705
Loss: 62.81438064575195 Accuracy: 0.9200000166893005
Loss: 88.81392669677734 Accuracy: 0.9124999642372131
Loss: 117.67169189453125 Accuracy: 0.9100000262260437
Total Loss: 138.13186645507812 Total Accuracy: 0.9079422354698181
..........Saving the model..........
========= Epoch 8 Training =========
tensor([[-3.5203,  2.7218]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1683.8140494823456
Train steps: 18000, Loss: 0.0019437245791777968
tensor([[-3.4932,  2.7050]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1723.9747376441956
Train steps: 18500, Loss: 0.0020309314131736755
tensor([[-3.6078,  2.7748]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1760.9496521949768
Train steps: 19000, Loss: 0.0016894364962354302
tensor([[-0.5774,  0.5551]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1796.9261598587036
Train 

tensor([[-3.7541,  2.9810]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3164.5295741558075
Train steps: 34000, Loss: 0.0011878109071403742
tensor([[-2.6833,  2.0959]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3200.678253889084
Train steps: 34500, Loss: 0.008367598988115788
tensor([[-3.5968,  2.8427]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3236.7662341594696
Train steps: 35000, Loss: 0.001595773035660386
tensor([[-3.9487,  3.0265]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3277.151768922806
Train steps: 35500, Loss: 0.0009344025747850537
========= Epoch 15 Testing =========
Loss: 26.79628562927246 Accuracy: 0.9199999570846558
Loss: 52.672542572021484 Accuracy: 0.9199999570846558
Loss: 86.89654541015625 Accuracy: 0.9166666865348816
Loss: 114.83529663085938 Accuracy: 0.9149999618530273
Loss: 149.27865600585938 Accuracy: 0.9140000343322754
Total Loss: 163.94456481933594 Total Accuracy: 0.911552369594574
..........Saving the model....

tensor([[ 2.6414, -2.1472]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4713.101106882095
Train steps: 51000, Loss: 0.008290164172649384
========= Epoch 22 Testing =========
Loss: 60.474578857421875 Accuracy: 0.8899999856948853
Loss: 104.91659545898438 Accuracy: 0.9049999713897705
Loss: 121.50708770751953 Accuracy: 0.9200000166893005
Loss: 152.88284301757812 Accuracy: 0.92249995470047
Loss: 169.81927490234375 Accuracy: 0.9300000667572021
Total Loss: 204.58465576171875 Total Accuracy: 0.9259927868843079
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-4.1492,  3.1976]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4788.030001163483
Train steps: 51500, Loss: 0.0006444760947488248
tensor([[-4.1155,  3.1868]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4826.887540817261
Train steps: 52000, Loss: 0.0006736631621606648
tensor([[ 2.0178, -1.6520]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4864.257985830307
Tra

Total Loss: 258.1542663574219 Total Accuracy: 0.9187725782394409
..........Saving the model..........
========= Epoch 30 Training =========
tensor([[-3.9555,  3.0828]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6364.3379855155945
Train steps: 67000, Loss: 0.0008772339788265526
tensor([[-3.9562,  3.1324]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6410.439783811569
Train steps: 67500, Loss: 0.000834236154332757
tensor([[-3.9832,  3.1358]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6455.761162996292
Train steps: 68000, Loss: 0.0008092228090390563
tensor([[-3.8154,  3.0557]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6499.106296300888
Train steps: 68500, Loss: 0.0010368215152993798
========= Epoch 30 Testing =========
Loss: 17.036046981811523 Accuracy: 0.9599999785423279
Loss: 90.90487670898438 Accuracy: 0.9099999666213989
Loss: 144.22195434570312 Accuracy: 0.9100000262260437
Loss: 196.3738555908203 Accuracy: 0.9099999666213989
Loss: 248

tensor([[ 3.6299, -3.1188]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8758.150728940964
Train steps: 84000, Loss: 0.0011717366287484765
========= Epoch 37 Testing =========
Loss: 65.63025665283203 Accuracy: 0.8999999761581421
Loss: 127.38700103759766 Accuracy: 0.9049999713897705
Loss: 210.2935028076172 Accuracy: 0.893333375453949
Loss: 265.16754150390625 Accuracy: 0.8999999761581421
Loss: 293.1153869628906 Accuracy: 0.9120000600814819
Total Loss: 306.9944152832031 Total Accuracy: 0.916967511177063
..........Saving the model..........
========= Epoch 38 Training =========
tensor([[ 3.7269, -3.2205]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8838.779330968857
Train steps: 84500, Loss: 0.0009606037638150156
tensor([[-4.1603,  3.2474]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8881.139319896698
Train steps: 85000, Loss: 0.0006063529872335494
tensor([[ 3.6478, -3.0984]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8921.980337142944
Train 

Total Loss: 306.91534423828125 Total Accuracy: 0.9187725782394409
..........Saving the model..........
========= Epoch 45 Training =========
tensor([[-4.3245,  3.3600]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10371.627479553223
Train steps: 100000, Loss: 0.00045980370487086475
tensor([[-4.0367,  3.1918]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10408.861201524734
Train steps: 100500, Loss: 0.0007253637886606157
tensor([[-4.1952,  3.2584]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10449.75361919403
Train steps: 101000, Loss: 0.0005791893927380443
tensor([[-4.1756,  3.2763]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10495.402685642242
Train steps: 101500, Loss: 0.0005801424849778414
tensor([[ 3.9154, -3.3987]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10533.488054990768
Train steps: 102000, Loss: 0.0006658005877397954
========= Epoch 45 Testing =========
Loss: 62.651371002197266 Accuracy: 0.9099999666213989
Loss: 10

tensor([[-4.3464,  3.3916]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11976.587812423706
Train steps: 116500, Loss: 0.00043585337698459625
tensor([[ 4.3146, -3.8320]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12019.228065013885
Train steps: 117000, Loss: 0.0002896366349887103
tensor([[-4.3566,  3.3863]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12057.16170668602
Train steps: 117500, Loss: 0.0004337085410952568
========= Epoch 52 Testing =========
Loss: 44.96299743652344 Accuracy: 0.9399999976158142
Loss: 74.90876770019531 Accuracy: 0.949999988079071
Loss: 165.1610565185547 Accuracy: 0.9266666769981384
Loss: 239.60107421875 Accuracy: 0.9199999570846558
Loss: 295.4269104003906 Accuracy: 0.9200000166893005
Total Loss: 325.1591491699219 Total Accuracy: 0.9205775856971741
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[-4.3606,  3.3947]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 12139.49669766426
Tra

========= Epoch 59 Testing =========
Loss: 32.95853042602539 Accuracy: 0.949999988079071
Loss: 114.02912139892578 Accuracy: 0.9300000071525574
Loss: 164.87820434570312 Accuracy: 0.9333333373069763
Loss: 243.4471435546875 Accuracy: 0.9249999523162842
Loss: 318.0376281738281 Accuracy: 0.9220000505447388
Total Loss: 352.5359191894531 Total Accuracy: 0.922382652759552
..........Saving the model..........
../data/eegmap_split_new/rest\train\hc\rest_hc_train_1.pt
../data/eegmap_split_new/rest\train\hc\rest_hc_train_1_hc_doc_label.pt
../data/eegmap_split_new/rest\test\hc\rest_hc_test_1.pt
../data/eegmap_split_new/rest\test\hc\rest_hc_test_1_hc_doc_label.pt
../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_1.pt
../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_1_hc_doc_label.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_1.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_1_hc_doc_label.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_1.pt
../data/eegmap_split

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.4685,  0.2082]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 40.058284759521484
Train steps: 500, Loss: 1.0877225399017334
tensor([[-0.4671,  0.1803]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 77.43317294120789
Train steps: 1000, Loss: 0.42093536257743835
tensor([[-0.6877,  0.3764]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 116.00225496292114
Train steps: 1500, Loss: 1.3605899810791016
tensor([[-0.6657,  0.3856]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 157.08825254440308
Train steps: 2000, Loss: 0.29973146319389343
========= Epoch 0 Testing =========
Loss: 64.08683013916016 Accuracy: 0.6599999666213989
Loss: 127.02745056152344 Accuracy: 0.6649999618530273
Loss: 183.31430053710938 Accuracy: 0.6966666579246521
Loss: 247.11990356445312 Accuracy: 0.6875
Loss: 304.7003173828125 Accuracy: 0.6980000138282776
Total Loss: 339.6654357910156 Total Accuracy: 0.6931408047676086
..........Saving t

========= Epoch 7 Testing =========
Loss: 52.69353103637695 Accuracy: 0.699999988079071
Loss: 102.98304748535156 Accuracy: 0.7149999737739563
Loss: 150.29391479492188 Accuracy: 0.7266666889190674
Loss: 214.80252075195312 Accuracy: 0.7174999713897705
Loss: 276.2511901855469 Accuracy: 0.7080000042915344
Total Loss: 293.7634582519531 Total Accuracy: 0.7202165722846985
..........Saving the model..........
========= Epoch 8 Training =========
tensor([[-1.3759,  1.1504]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1756.9534995555878
Train steps: 18000, Loss: 0.07691449671983719
tensor([[ 0.0416, -0.1441]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1798.9452018737793
Train steps: 18500, Loss: 0.6045823097229004
tensor([[-1.4001,  1.1891]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1836.7457263469696
Train steps: 19000, Loss: 0.07239056378602982
tensor([[ 0.1832, -0.3332]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1877.7901825904846
Train ste

tensor([[-2.0800,  1.7768]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3318.26092171669
Train steps: 34000, Loss: 0.020914960652589798
tensor([[ 1.3616, -1.4834]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3357.5782124996185
Train steps: 34500, Loss: 2.901479482650757
tensor([[-2.4281,  2.1853]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3395.0206990242004
Train steps: 35000, Loss: 0.009870058856904507
tensor([[-2.6205,  2.3456]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3434.567478656769
Train steps: 35500, Loss: 0.006946342531591654
========= Epoch 15 Testing =========
Loss: 67.67609405517578 Accuracy: 0.75
Loss: 149.49896240234375 Accuracy: 0.7299999594688416
Loss: 220.82086181640625 Accuracy: 0.753333330154419
Loss: 270.328369140625 Accuracy: 0.7649999856948853
Loss: 342.912353515625 Accuracy: 0.7680000066757202
Total Loss: 385.2479248046875 Total Accuracy: 0.7617328763008118
..........Saving the model..........
========= Epoch 1

========= Epoch 22 Testing =========
Loss: 113.82819366455078 Accuracy: 0.7400000095367432
Loss: 228.6504669189453 Accuracy: 0.7400000095367432
Loss: 332.479248046875 Accuracy: 0.746666669845581
Loss: 467.1007385253906 Accuracy: 0.7400000095367432
Loss: 614.4049682617188 Accuracy: 0.7380000352859497
Total Loss: 697.662109375 Total Accuracy: 0.7346570491790771
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-3.7466,  3.5064]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5045.933176994324
Train steps: 51500, Loss: 0.0007077334448695183
tensor([[-3.8754,  3.5902]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5085.536896467209
Train steps: 52000, Loss: 0.0005722792120650411
tensor([[-4.0551,  3.6646]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5128.128883838654
Train steps: 52500, Loss: 0.0004438368487171829
tensor([[-3.4865,  3.2030]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5165.982898950577
Train steps

tensor([[-3.9309,  3.6475]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6624.722781181335
Train steps: 67500, Loss: 0.0005112771177664399
tensor([[-5.2917,  4.9643]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6664.988965272903
Train steps: 68000, Loss: 3.516612196108326e-05
tensor([[-2.7590,  2.6057]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6707.2255482673645
Train steps: 68500, Loss: 0.0046678148210048676
========= Epoch 30 Testing =========
Loss: 144.6490936279297 Accuracy: 0.7999999523162842
Loss: 285.5166320800781 Accuracy: 0.7999999523162842
Loss: 447.3934631347656 Accuracy: 0.7800000309944153
Loss: 576.1484985351562 Accuracy: 0.7724999785423279
Loss: 739.6576538085938 Accuracy: 0.7600000500679016
Total Loss: 824.1502075195312 Total Accuracy: 0.7635378837585449
..........Saving the model..........
========= Epoch 31 Training =========
tensor([[-4.5303,  4.2127]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6786.588487625122
Train

Loss: 338.30255126953125 Accuracy: 0.6699999570846558
Loss: 541.5173950195312 Accuracy: 0.7249999642372131
Loss: 792.8624267578125 Accuracy: 0.7266666889190674
Loss: 1045.0220947265625 Accuracy: 0.7299999594688416
Loss: 1351.2193603515625 Accuracy: 0.7200000286102295
Total Loss: 1435.4759521484375 Total Accuracy: 0.7238267064094543
..........Saving the model..........
========= Epoch 38 Training =========
tensor([[ 5.2185, -5.2425]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8300.409740447998
Train steps: 84500, Loss: 2.8609820219571702e-05
tensor([[ 5.1223, -5.1039]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8341.06725859642
Train steps: 85000, Loss: 3.6238969187252223e-05
tensor([[-6.7041,  6.4193]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8378.877685546875
Train steps: 85500, Loss: 2.0265558760002023e-06
tensor([[-6.6435,  6.2779]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8418.931239128113
Train steps: 86000, Loss: 2.503391897

tensor([[-7.8037,  7.4228]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9889.159153461456
Train steps: 100500, Loss: 2.3841856489070778e-07
tensor([[-8.9612,  8.4949]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9928.838760614395
Train steps: 101000, Loss: 0.0
tensor([[-6.5486,  6.1966]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9970.649029016495
Train steps: 101500, Loss: 2.8610190838662675e-06
tensor([[-7.7625,  7.6014]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10013.385420084
Train steps: 102000, Loss: 2.3841856489070778e-07
========= Epoch 45 Testing =========
Loss: 361.1264343261719 Accuracy: 0.75
Loss: 660.6940307617188 Accuracy: 0.7450000047683716
Loss: 1073.83056640625 Accuracy: 0.7400000095367432
Loss: 1554.43896484375 Accuracy: 0.7174999713897705
Loss: 1929.2889404296875 Accuracy: 0.7220000624656677
Total Loss: 2110.6591796875 Total Accuracy: 0.7238267064094543
..........Saving the model..........
========= Epoch 46 Trainin

Loss: 1756.4461669921875 Accuracy: 0.7640000581741333
Total Loss: 1941.4517822265625 Total Accuracy: 0.7635378837585449
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[-10.5151,   9.9188]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11627.291028261185
Train steps: 118000, Loss: 0.0
tensor([[-10.2169,   9.6250]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11667.030612945557
Train steps: 118500, Loss: 0.0
tensor([[-10.0717,   9.5172]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11708.00587105751
Train steps: 119000, Loss: 0.0
tensor([[ 9.1830, -9.1559]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11745.689373016357
Train steps: 119500, Loss: 0.0
========= Epoch 53 Testing =========
Loss: 425.6991882324219 Accuracy: 0.7299999594688416
Loss: 810.1959228515625 Accuracy: 0.73499995470047
Loss: 1120.267578125 Accuracy: 0.753333330154419
Loss: 1499.5615234375 Accuracy: 0.7549999952316284
Loss: 1735.502563476562

  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.4875,  0.3218]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 39.19707918167114
Train steps: 500, Loss: 1.1774672269821167
tensor([[-0.3310,  0.2030]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 78.51029586791992
Train steps: 1000, Loss: 0.4613945782184601
tensor([[-0.4050,  0.2522]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 117.19552254676819
Train steps: 1500, Loss: 1.0748008489608765
tensor([[-0.7232,  0.5235]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 160.24657273292542
Train steps: 2000, Loss: 1.4993720054626465
========= Epoch 0 Testing =========
Loss: 57.083377838134766 Accuracy: 0.7400000095367432
Loss: 110.95748138427734 Accuracy: 0.7599999904632568
Loss: 183.26712036132812 Accuracy: 0.699999988079071
Loss: 242.21006774902344 Accuracy: 0.7049999833106995
Loss: 307.2861328125 Accuracy: 0.6940000057220459
Total Loss: 340.888427734375 Total Accuracy: 0.6931408047676086
..........Sav

========= Epoch 7 Testing =========
Loss: 59.51667022705078 Accuracy: 0.7099999785423279
Loss: 121.3100357055664 Accuracy: 0.699999988079071
Loss: 181.92568969726562 Accuracy: 0.699999988079071
Loss: 242.94378662109375 Accuracy: 0.699999988079071
Loss: 304.06964111328125 Accuracy: 0.6960000395774841
Total Loss: 337.53497314453125 Total Accuracy: 0.6931408047676086
..........Saving the model..........
========= Epoch 8 Training =========
tensor([[-0.3703,  0.2777]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1756.7750022411346
Train steps: 18000, Loss: 0.42075151205062866
tensor([[-0.5270,  0.3905]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1799.402881860733
Train steps: 18500, Loss: 1.2536364793777466
tensor([[-0.4159,  0.2917]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1838.312637090683
Train steps: 19000, Loss: 0.4006805419921875
tensor([[-0.5716,  0.3838]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1880.206830739975
Train steps: 1

tensor([[-0.6729,  0.5200]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3305.0087552070618
Train steps: 34000, Loss: 0.2649470865726471
tensor([[-1.0395,  0.7741]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3343.9363718032837
Train steps: 34500, Loss: 0.1510625183582306
tensor([[ 0.0448, -0.0033]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3388.5707399845123
Train steps: 35000, Loss: 0.6694027185440063
tensor([[-1.1023,  0.8674]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3429.46817278862
Train steps: 35500, Loss: 0.13058467209339142
========= Epoch 15 Testing =========
Loss: 56.82704544067383 Accuracy: 0.7199999690055847
Loss: 112.31385803222656 Accuracy: 0.7149999737739563
Loss: 170.302490234375 Accuracy: 0.7100000381469727
Loss: 241.9738311767578 Accuracy: 0.6924999952316284
Loss: 297.9288635253906 Accuracy: 0.6980000138282776
Total Loss: 330.6279602050781 Total Accuracy: 0.6877256035804749
..........Saving the model..........
=====

========= Epoch 22 Testing =========
Loss: 84.96398162841797 Accuracy: 0.7299999594688416
Loss: 169.40911865234375 Accuracy: 0.6850000023841858
Loss: 261.33685302734375 Accuracy: 0.6600000262260437
Loss: 342.1123352050781 Accuracy: 0.6524999737739563
Loss: 427.1143493652344 Accuracy: 0.6540000438690186
Total Loss: 468.1159973144531 Total Accuracy: 0.6534296274185181
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-3.4633,  2.7451]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5032.687153100967
Train steps: 51500, Loss: 0.0020103498827666044
tensor([[-2.1328,  1.6427]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5070.443139791489
Train steps: 52000, Loss: 0.022666888311505318
tensor([[-3.8820,  3.1004]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5108.468935728073
Train steps: 52500, Loss: 0.0009276139317080379
tensor([[-2.3167,  1.6803]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5146.414236307144
Train

tensor([[ 2.1035, -2.2501]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6575.150336027145
Train steps: 67500, Loss: 0.012779129669070244
tensor([[-3.6341,  2.8771]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6619.353101015091
Train steps: 68000, Loss: 0.0014855550834909081
tensor([[-4.8618,  4.0047]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6662.2310247421265
Train steps: 68500, Loss: 0.00014101465058047324
========= Epoch 30 Testing =========
Loss: 135.15797424316406 Accuracy: 0.699999988079071
Loss: 278.8743896484375 Accuracy: 0.6699999570846558
Loss: 387.6249694824219 Accuracy: 0.6899999976158142
Loss: 503.7191162109375 Accuracy: 0.6974999904632568
Loss: 635.2570190429688 Accuracy: 0.690000057220459
Total Loss: 733.0786743164062 Total Accuracy: 0.6823104619979858
..........Saving the model..........
========= Epoch 31 Training =========
tensor([[-3.5198,  2.7011]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6743.6518471241
Train st

Loss: 237.09266662597656 Accuracy: 0.6800000071525574
Loss: 403.5482177734375 Accuracy: 0.7149999737739563
Loss: 644.2301635742188 Accuracy: 0.7166666984558105
Loss: 827.0921020507812 Accuracy: 0.7224999666213989
Loss: 1089.517822265625 Accuracy: 0.6960000395774841
Total Loss: 1211.0382080078125 Total Accuracy: 0.6949458718299866
..........Saving the model..........
========= Epoch 38 Training =========
tensor([[-6.7360,  5.7434]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8253.125793933868
Train steps: 84500, Loss: 3.814689989667386e-06
tensor([[ 4.9185, -4.9650]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8293.54112815857
Train steps: 85000, Loss: 5.102027716930024e-05
tensor([[-7.0847,  6.1093]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8336.4609978199
Train steps: 85500, Loss: 1.9073467001362587e-06
tensor([[-5.5804,  4.7737]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8375.233810424805
Train steps: 86000, Loss: 3.182837463100441

tensor([[-7.3645,  6.4454]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9820.652542829514
Train steps: 100500, Loss: 9.536738616588991e-07
tensor([[ 5.3884, -5.1280]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9861.76843547821
Train steps: 101000, Loss: 2.706014311115723e-05
tensor([[-5.7605,  4.9826]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9898.672903060913
Train steps: 101500, Loss: 2.1576648578047752e-05
tensor([[-6.2314,  5.3588]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9935.820908784866
Train steps: 102000, Loss: 9.298280929215252e-06
========= Epoch 45 Testing =========
Loss: 202.89651489257812 Accuracy: 0.75
Loss: 415.0228576660156 Accuracy: 0.7149999737739563
Loss: 656.6476440429688 Accuracy: 0.7166666984558105
Loss: 964.8770751953125 Accuracy: 0.6949999928474426
Loss: 1142.10546875 Accuracy: 0.7040000557899475
Total Loss: 1288.7723388671875 Total Accuracy: 0.6949458718299866
..........Saving the model..........
========

tensor([[-9.1927,  8.2423]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11437.844609737396
Train steps: 117500, Loss: 0.0
========= Epoch 52 Testing =========
Loss: 315.5938720703125 Accuracy: 0.7299999594688416
Loss: 606.6088256835938 Accuracy: 0.7400000095367432
Loss: 963.0263061523438 Accuracy: 0.7233333587646484
Loss: 1306.6142578125 Accuracy: 0.7099999785423279
Loss: 1734.994384765625 Accuracy: 0.6980000138282776
Total Loss: 1901.308837890625 Total Accuracy: 0.6967508792877197
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[-9.0204,  8.1150]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11516.676668643951
Train steps: 118000, Loss: 0.0
tensor([[ 7.1150, -6.7605]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11555.606609106064
Train steps: 118500, Loss: 9.536738048154803e-07
tensor([[-9.1201,  8.2267]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11593.017344713211
Train steps: 119000, Loss: 0.0
tensor

../data/eegmap_split_new/rest\train\mcs\rest_mcs_train_3_hc_doc_label.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_3.pt
../data/eegmap_split_new/rest\test\mcs\rest_mcs_test_3_hc_doc_label.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_3.pt
../data/eegmap_split_new/rest\train\uws\rest_uws_train_3_hc_doc_label.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_3.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_3_hc_doc_label.pt
torch.Size([2221, 2400, 9, 11])
torch.Size([2221])
torch.Size([554, 2400, 9, 11])
torch.Size([554])


  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.6770,  0.5018]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 38.89933490753174
Train steps: 500, Loss: 0.2682228684425354
tensor([[-1.6976,  1.7828]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 77.31376910209656
Train steps: 1000, Loss: 0.03033032827079296
tensor([[-1.7895,  1.8366]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 115.73601078987122
Train steps: 1500, Loss: 0.026271184906363487
tensor([[-1.0222,  1.0004]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 155.88078498840332
Train steps: 2000, Loss: 0.12426624447107315
========= Epoch 0 Testing =========
Loss: 50.152889251708984 Accuracy: 0.8199999928474426
Loss: 94.63043975830078 Accuracy: 0.824999988079071
Loss: 142.1671600341797 Accuracy: 0.8133333325386047
Loss: 180.68658447265625 Accuracy: 0.8125
Loss: 214.726318359375 Accuracy: 0.8180000185966492
Total Loss: 232.39297485351562 Total Accuracy: 0.826714813709259
..........Saving the

========= Epoch 7 Testing =========
Loss: 35.34559631347656 Accuracy: 0.8499999642372131
Loss: 68.21969604492188 Accuracy: 0.8650000095367432
Loss: 104.19518280029297 Accuracy: 0.8666666746139526
Loss: 146.97854614257812 Accuracy: 0.8574999570846558
Loss: 187.32473754882812 Accuracy: 0.8560000658035278
Total Loss: 201.01516723632812 Total Accuracy: 0.8610108494758606
..........Saving the model..........
========= Epoch 8 Training =========
tensor([[-1.5048,  1.5191]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1698.478628396988
Train steps: 18000, Loss: 0.047465674579143524
tensor([[-1.4397,  1.4363]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1742.1441593170166
Train steps: 18500, Loss: 2.930858850479126
tensor([[ 2.3098, -2.7589]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1785.717850446701
Train steps: 19000, Loss: 0.0062712072394788265
tensor([[-1.5314,  1.5508]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1828.8129661083221
Train s

tensor([[-2.2071,  2.3103]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3223.9190607070923
Train steps: 34000, Loss: 0.010857906192541122
tensor([[-1.7890,  1.8539]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3265.6957697868347
Train steps: 34500, Loss: 0.02583901770412922
tensor([[ 2.9007, -3.2951]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3305.081068754196
Train steps: 35000, Loss: 0.002035809215158224
tensor([[-1.9170,  2.0066]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3345.7412626743317
Train steps: 35500, Loss: 0.019575266167521477
========= Epoch 15 Testing =========
Loss: 45.21128845214844 Accuracy: 0.85999995470047
Loss: 75.6153335571289 Accuracy: 0.8899999856948853
Loss: 109.21114349365234 Accuracy: 0.8799999952316284
Loss: 152.16229248046875 Accuracy: 0.8700000047683716
Loss: 198.21116638183594 Accuracy: 0.8640000224113464
Total Loss: 223.3737335205078 Total Accuracy: 0.8628158569335938
..........Saving the model.........

========= Epoch 22 Testing =========
Loss: 61.239662170410156 Accuracy: 0.8499999642372131
Loss: 74.5865478515625 Accuracy: 0.9049999713897705
Loss: 113.5190658569336 Accuracy: 0.9066666960716248
Loss: 160.54957580566406 Accuracy: 0.8974999785423279
Loss: 241.36471557617188 Accuracy: 0.8760000467300415
Total Loss: 261.346435546875 Total Accuracy: 0.8754512667655945
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[-2.9431,  3.0842]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4899.111166477203
Train steps: 51500, Loss: 0.0024090574588626623
tensor([[-2.5962,  2.7416]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4936.665807962418
Train steps: 52000, Loss: 0.004794885404407978
tensor([[-2.4895,  2.5477]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4975.401785135269
Train steps: 52500, Loss: 0.006470799446105957
tensor([[ 3.4635, -3.7977]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 5012.782780647278
Train s

tensor([[-2.9737,  3.1364]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6403.783758640289
Train steps: 67500, Loss: 0.002217930741608143
tensor([[ 4.0440, -4.2763]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6439.078852415085
Train steps: 68000, Loss: 0.00024351490719709545
tensor([[-3.1921,  3.3898]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6473.084197044373
Train steps: 68500, Loss: 0.001384253497235477
========= Epoch 30 Testing =========
Loss: 47.178733825683594 Accuracy: 0.8899999856948853
Loss: 118.03923034667969 Accuracy: 0.8700000047683716
Loss: 155.68734741210938 Accuracy: 0.8833333253860474
Loss: 233.6070098876953 Accuracy: 0.8700000047683716
Loss: 292.77569580078125 Accuracy: 0.8720000386238098
Total Loss: 319.7472839355469 Total Accuracy: 0.8736461997032166
..........Saving the model..........
========= Epoch 31 Training =========
tensor([[-3.2396,  3.4020]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6544.467147111893
Tra

Loss: 79.80786895751953 Accuracy: 0.8899999856948853
Loss: 171.83056640625 Accuracy: 0.8799999952316284
Loss: 296.3013610839844 Accuracy: 0.8566666841506958
Loss: 374.3834533691406 Accuracy: 0.8675000071525574
Loss: 454.1198425292969 Accuracy: 0.8700000643730164
Total Loss: 476.0950012207031 Total Accuracy: 0.8754512667655945
..........Saving the model..........
========= Epoch 38 Training =========
tensor([[-3.9449,  4.1867]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7945.560816287994
Train steps: 84500, Loss: 0.00029404606902971864
tensor([[ 5.6030, -5.9007]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7984.321529865265
Train steps: 85000, Loss: 1.0132738680113107e-05
tensor([[-4.2529,  4.6104]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8021.486846446991
Train steps: 85500, Loss: 0.00014149141497910023
tensor([[-4.8820,  5.2277]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 8057.452592611313
Train steps: 86000, Loss: 4.06495419156271

tensor([[-6.6787,  7.0860]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9399.663392066956
Train steps: 100500, Loss: 1.0728830375228426e-06
tensor([[ 7.2558, -7.5768]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9435.096826314926
Train steps: 101000, Loss: 3.576278118089249e-07
tensor([[-6.9624,  7.4435]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9476.004598379135
Train steps: 101500, Loss: 5.960462772236497e-07
tensor([[-7.1690,  7.6039]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9512.274154424667
Train steps: 102000, Loss: 3.576278118089249e-07
========= Epoch 45 Testing =========
Loss: 143.6934814453125 Accuracy: 0.8399999737739563
Loss: 270.4674987792969 Accuracy: 0.8700000047683716
Loss: 387.9479064941406 Accuracy: 0.8700000047683716
Loss: 539.2247924804688 Accuracy: 0.8700000047683716
Loss: 631.0013427734375 Accuracy: 0.878000020980835
Total Loss: 717.3419799804688 Total Accuracy: 0.8754512667655945
..........Saving the model...

Loss: 303.9884338378906 Accuracy: 0.8949999809265137
Loss: 600.5230712890625 Accuracy: 0.8633333444595337
Loss: 723.890869140625 Accuracy: 0.8725000023841858
Loss: 908.878662109375 Accuracy: 0.8760000467300415
Total Loss: 1031.26953125 Total Accuracy: 0.8718411326408386
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[-8.6991,  8.8977]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11007.906960010529
Train steps: 118000, Loss: 0.0
tensor([[-9.1520,  9.3174]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11044.616335868835
Train steps: 118500, Loss: 0.0
tensor([[-9.1125,  9.2179]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11083.273350715637
Train steps: 119000, Loss: 0.0
tensor([[-9.2700,  9.3568]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 11119.693815469742
Train steps: 119500, Loss: 0.0
========= Epoch 53 Testing =========
Loss: 181.03565979003906 Accuracy: 0.8799999952316284
Loss: 345.2449035644531 Acc

../data/eegmap_split_new/rest\test\uws\rest_uws_test_4.pt
../data/eegmap_split_new/rest\test\uws\rest_uws_test_4_hc_doc_label.pt
torch.Size([2221, 2400, 9, 11])
torch.Size([2221])
torch.Size([554, 2400, 9, 11])
torch.Size([554])


  0%|          | 0/60 [00:00<?, ?it/s]

========= Epoch 0 Training =========
tensor([[-0.5536,  0.4351]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 35.60583734512329
Train steps: 500, Loss: 0.31633293628692627
tensor([[-0.4430,  0.3020]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 71.07224750518799
Train steps: 1000, Loss: 0.38847485184669495
tensor([[-0.4076,  0.3190]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 108.75410628318787
Train steps: 1500, Loss: 0.39442795515060425
tensor([[-0.3250,  0.2112]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 145.86093068122864
Train steps: 2000, Loss: 0.4605639576911926
========= Epoch 0 Testing =========
Loss: 62.849266052246094 Accuracy: 0.6800000071525574
Loss: 123.97526550292969 Accuracy: 0.6949999928474426
Loss: 186.8025360107422 Accuracy: 0.6833333373069763
Loss: 247.2450714111328 Accuracy: 0.6924999952316284
Loss: 312.5091857910156 Accuracy: 0.6800000071525574
Total Loss: 343.1070251464844 Total Accuracy: 0.6931408047676086
.......

========= Epoch 7 Testing =========
Loss: 56.65884780883789 Accuracy: 0.6800000071525574
Loss: 112.89649200439453 Accuracy: 0.6949999928474426
Loss: 164.47183227539062 Accuracy: 0.7100000381469727
Loss: 220.11036682128906 Accuracy: 0.7074999809265137
Loss: 278.6083679199219 Accuracy: 0.7000000476837158
Total Loss: 309.95318603515625 Total Accuracy: 0.6985559463500977
..........Saving the model..........
========= Epoch 8 Training =========
tensor([[-0.0705, -0.0711]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1603.323340177536
Train steps: 18000, Loss: 0.6928160190582275
tensor([[-0.6439,  0.4979]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1640.4158251285553
Train steps: 18500, Loss: 0.2770797312259674
tensor([[-1.1339,  0.9945]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1677.9705722332
Train steps: 19000, Loss: 0.11246106773614883
tensor([[-0.1961,  0.0107]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 1715.666851758957
Train steps: 

tensor([[-1.6773,  1.3465]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3038.520167827606
Train steps: 34000, Loss: 0.04747386649250984
tensor([[-1.3608,  1.0086]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3076.9949560165405
Train steps: 34500, Loss: 0.08941660821437836
tensor([[-1.9346,  1.5963]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3113.418394804001
Train steps: 35000, Loss: 0.028857508674263954
tensor([[-1.3122,  0.9173]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 3150.0362141132355
Train steps: 35500, Loss: 0.10217783600091934
========= Epoch 15 Testing =========
Loss: 46.46722412109375 Accuracy: 0.7999999523162842
Loss: 95.62452697753906 Accuracy: 0.7799999713897705
Loss: 151.97584533691406 Accuracy: 0.7599999904632568
Loss: 196.2030487060547 Accuracy: 0.7774999737739563
Loss: 246.08108520507812 Accuracy: 0.7820000648498535
Total Loss: 273.65802001953125 Total Accuracy: 0.7743682265281677
..........Saving the model.........

========= Epoch 22 Testing =========
Loss: 55.16135787963867 Accuracy: 0.75
Loss: 116.34610748291016 Accuracy: 0.73499995470047
Loss: 159.57867431640625 Accuracy: 0.7633333802223206
Loss: 214.17222595214844 Accuracy: 0.7649999856948853
Loss: 266.26080322265625 Accuracy: 0.7680000066757202
Total Loss: 296.35382080078125 Total Accuracy: 0.7671480178833008
..........Saving the model..........
========= Epoch 23 Training =========
tensor([[ 0.8839, -1.5243]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4626.577824115753
Train steps: 51500, Loss: 0.08615650981664658
tensor([[-2.1423,  1.5459]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4665.4758932590485
Train steps: 52000, Loss: 3.7129440307617188
tensor([[ 0.8538, -1.5741]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4702.405776262283
Train steps: 52500, Loss: 0.08454256504774094
tensor([[-2.0981,  1.5327]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 4739.25706577301
Train steps: 53000, Loss

tensor([[-1.5568,  0.6751]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6067.087587594986
Train steps: 67500, Loss: 0.10194984823465347
tensor([[-3.0078,  2.2565]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6104.659090518951
Train steps: 68000, Loss: 0.005159396678209305
tensor([[-2.8824,  2.3056]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6141.556690692902
Train steps: 68500, Loss: 0.005567639134824276
========= Epoch 30 Testing =========
Loss: 81.80345153808594 Accuracy: 0.6800000071525574
Loss: 134.4086456298828 Accuracy: 0.7549999952316284
Loss: 199.9620361328125 Accuracy: 0.7733333706855774
Loss: 253.94857788085938 Accuracy: 0.7774999737739563
Loss: 302.9684143066406 Accuracy: 0.7880000472068787
Total Loss: 324.70794677734375 Total Accuracy: 0.7906137108802795
..........Saving the model..........
========= Epoch 31 Training =========
tensor([[-2.0936,  1.3248]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 6213.604974031448
Train st

Loss: 48.958370208740234 Accuracy: 0.8299999833106995
Loss: 111.87884521484375 Accuracy: 0.8050000071525574
Loss: 213.9254150390625 Accuracy: 0.7433333396911621
Loss: 278.02337646484375 Accuracy: 0.7475000023841858
Loss: 332.36444091796875 Accuracy: 0.7560000419616699
Total Loss: 363.48590087890625 Total Accuracy: 0.7599278092384338
..........Saving the model..........
========= Epoch 38 Training =========
tensor([[-3.3055,  2.3971]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7655.8865559101105
Train steps: 84500, Loss: 0.003331826301291585
tensor([[ 1.9747, -2.7864]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7692.167094945908
Train steps: 85000, Loss: 0.008520321920514107
tensor([[-3.2238,  2.4154]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7731.431757926941
Train steps: 85500, Loss: 0.0035495867487043142
tensor([[-3.3083,  2.8127]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 7768.452295541763
Train steps: 86000, Loss: 0.00219378457

tensor([[-3.4586,  2.7834]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9135.133600711823
Train steps: 100500, Loss: 0.0019440813921391964
tensor([[-2.9118,  2.0315]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9175.447442531586
Train steps: 101000, Loss: 0.007106266915798187
tensor([[-3.2463,  2.5384]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9213.687956809998
Train steps: 101500, Loss: 0.003069334663450718
tensor([[ 0.7656, -1.7127]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 9252.235347032547
Train steps: 102000, Loss: 0.08055286854505539
========= Epoch 45 Testing =========
Loss: 38.313114166259766 Accuracy: 0.8799999952316284
Loss: 124.05616760253906 Accuracy: 0.8149999976158142
Loss: 180.09539794921875 Accuracy: 0.8166666626930237
Loss: 255.2288055419922 Accuracy: 0.8100000023841858
Loss: 325.20843505859375 Accuracy: 0.8060000538825989
Total Loss: 376.2945861816406 Total Accuracy: 0.7906137108802795
..........Saving the model...

tensor([[-3.4603,  2.5755]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10708.665656805038
Train steps: 117500, Loss: 0.002388721564784646
========= Epoch 52 Testing =========
Loss: 46.15586853027344 Accuracy: 0.8799999952316284
Loss: 113.16410064697266 Accuracy: 0.85999995470047
Loss: 209.93405151367188 Accuracy: 0.8233333826065063
Loss: 283.0283203125 Accuracy: 0.8199999928474426
Loss: 364.2430114746094 Accuracy: 0.8140000104904175
Total Loss: 399.9912414550781 Total Accuracy: 0.8140794038772583
..........Saving the model..........
========= Epoch 53 Training =========
tensor([[ 2.8278, -3.7338]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10781.839492082596
Train steps: 118000, Loss: 0.00141258561052382
tensor([[-3.7802,  3.0581]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10820.57520699501
Train steps: 118500, Loss: 0.0010713557712733746
tensor([[-4.0272,  3.5334]], device='cuda:0', grad_fn=<AddmmBackward0>)
Train time: 10859.611310958862
Train 

Total Loss: 441.657958984375 Total Accuracy: 0.8122743368148804
..........Saving the model..........
